import { MyButton, Title, Selector, LeftTab } from "framework/widgets.slint";
import { NumPad } from "numpad.slint";
import { AppState, AppBackend, ControlState, SpoolScaleState } from "app.slint";

export component CoreEstimate inherits Rectangle {
    background: white;
    border-color: black;
    border-width: 1px;
    VerticalLayout {
        padding-left: 10px;
        padding-right: 10px;
        padding-top: 5px;
        padding-bottom: 5px;
        spacing: 8px;
        VerticalLayout {
            spacing: 0px;
            Text {
                vertical-alignment: center;
                height: 30px;
                text: "Use this estimate only with unused spools!";
                font-size: 20px;
            }

            Text {
                vertical-alignment: top;
                height: 24px;
                text: "Select full spool listed/advertised weight";
                font-size: 20px;
            }
        }

        HorizontalLayout {
            preferred-width: 1000px;
            padding-left: 10px;
            padding-right: 10px;
            alignment: space-between;
            function select(text: string) {
                one.pushed = false;
                half.pushed = false;
                threeq.pushed = false;
                if text == "1kg" {
                    one.pushed = true;
                }
                if text == "750g" {
                    threeq.pushed = true;
                }
                if text == "500g" {
                    half.pushed = true;
                }
            }
            one := MyButton {
                height: 56px;
                width: 100px;
                text: "1kg";
                clicked => {
                    select(self.text);
                }
            }

            threeq := MyButton {
                height: 56px;
                width: 100px;
                text: "750g";
                clicked => {
                    select(self.text);
                }
            }

            half := MyButton {
                height: 56px;
                width: 100px;
                text: "500g";
                clicked => {
                    select(self.text);
                }
            }
        }

        HorizontalLayout {
            padding-left: 10px;
            padding-right: 10px;
            spacing: 20px;
            VerticalLayout {
                spacing: 10px;
                Text {
                    height: 24px;
                    vertical-alignment: top;
                    text: "Current measured weight";
                    font-size: 20px;
                }

                current-measured-weight := Rectangle {
                    width: 264px;
                    height: 30px;
                    border-color: black;
                    border-width: 1px;
                    background: AppState.spool-scale-state == SpoolScaleState.Disconnected || AppState.spool-scale-state == SpoolScaleState.Uncalibrated ? orangered : AppState.spool-scale-state == SpoolScaleState.Connected ? lightgreen : AppState.spool-scale-state == SpoolScaleState.Loaded && !AppState.spool-scale-weight-stable ? yellow : lightskyblue;
                    Text {
                        font-size: 20px;
                        text: AppState.spool-scale-state == SpoolScaleState.Disconnected ? "Scale Disconnected" : AppState.spool-scale-state == SpoolScaleState.Uncalibrated ? "Scale Not Calibrated" : AppState.spool-scale-state == SpoolScaleState.Connected ? "Scale Connected" : AppState.spool-scale-state == SpoolScaleState.Loaded ? "\{AppState.spool-scale-weight}g" : "";
                    }
                }

                Text {
                    height: 24px;
                    vertical-alignment: top;
                    text: "Estimated Spool Core Weight";
                    font-size: 20px;
                }

                displayed-weight := Rectangle {
                    property <int> calculated-core: AppState.spool-scale-weight - (one.pushed ? 1000 : half.pushed ? 500 : threeq.pushed ? 750 : AppState.spool-scale-weight);
                    width: 264px;
                    height: 30px;
                    border-color: black;
                    border-width: 1px;
                    background: lightskyblue;
                    Text {
                        font-size: 20px;
                        text: calculated-core > 0 ? "\{calculated-core}" : "";
                    }
                }
            }

            VerticalLayout {
                Text { }

                MyButton {
                    enabled: displayed-weight.calculated-core > 0;
                    height: 100px;
                    text: "Ok";
                    clicked => {
                        AppState.encode-set-core-info(displayed-weight.calculated-core, AppState.spool-scale-weight, "");
                        AppState.encoding-spool-core-visible = false;
                    }
                }
            }
        }
    }
}

export component SelectIfNewSpool inherits Rectangle {
    callback cancel-clicked;
    callback yes-clicked;
    callback no-clicked;
    background: white;
    VerticalLayout {
        alignment: center;
        padding: 20px;
        HorizontalLayout {
            VerticalLayout {
                width: parent.width / 2;
                measured-weight-title := Text {
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    height: 30px;
                    text: "Spool measured weight";
                    font-size: 20px;
                }

                HorizontalLayout {
                    alignment: center;
                    Rectangle {
                        width: 155px;
                        height: 30px;
                        background: lightskyblue;
                        border-color: black;
                        border-width: 1px;
                        Text {
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            height: 30px;
                            text: "\{AppState.spool-scale-weight}g";
                            font-size: 20px;
                        }
                    }
                }
            }

            VerticalLayout {
                width: parent.width / 2;
                core-weight-title := Text {
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    height: 30px;
                    text: "Entered core weight";
                    font-size: 20px;
                }

                HorizontalLayout {
                    alignment: center;
                    Rectangle {
                        width: 155px;
                        height: 30px;
                        background: lightskyblue;
                        border-color: black;
                        border-width: 1px;
                        Text {
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            height: 30px;
                            text: "\{AppState.core-weight-to-encode-after-select-if-new}g";
                            font-size: 20px;
                        }
                    }
                }
            }
        }

        Text {
            vertical-alignment: center;
            height: 30px;
            text: "";
            font-size: 20px;
        }

        Text {
            vertical-alignment: center;
            height: 30px;
            text: "Encode this as a new Spool?";
            font-size: 20px;
        }

        Text {
            vertical-alignment: center;
            height: 30px;
            text: "Press 'Yes' only if this is an unused Spool";
            font-size: 20px;
        }

        Text {
            vertical-alignment: center;
            height: 30px;
            text: "";
            font-size: 20px;
        }

        HorizontalLayout {
            padding-top: 10px;
            alignment: center;
            spacing: 40px;
            yes := MyButton {
                height: 56px;
                width: 120px;
                text: "Yes";
                clicked => {
                    root.yes-clicked();
                }
            }

            no := MyButton {
                height: 56px;
                width: 120px;
                text: "No";
                clicked => {
                    root.no-clicked();
                }
            }

            cancel := MyButton {
                height: 56px;
                width: 120px;
                text: "Cancel";
                clicked => {
                    // root.state = SpoolCoreWeightState.EntryTabs;
                    root.cancel-clicked()
                }
            }
        }
    }
}

export component Keyboard inherits Rectangle {
    callback clicked-ok;
    callback clicked-cancel();
    in-out property <string> typed-text;
    property <[[string]]> keys: [
        ["A", "B", "C", "D", "E", "F", "G", "H"],
        ["I", "J", "L", "M", "N", "O", "P", "Q"],
        ["R", "S", "T", "U", "V", "W", "X", "Y"],
        ["Z", "3"],
    ];
    callback key-clicked(char: string);
    background: white;
    VerticalLayout {
        Rectangle {
            height: 56px;
            width: root.width;
            Text {
                text: root.typed-text;
                font-size: 20px;
            }
        }

        for row[y] in keys: HorizontalLayout {
            for col in row: MyButton {
                height: 56px;
                width: 60px;
                text: col;
                clicked => {
                    root.typed-text = "\{root.typed-text}\{self.text}";
                }
            }
        }
    }

    HorizontalLayout {
        x: root.width - 60px * 4;
        y: root.height - 56px;
        MyButton {
            width: 120px;
            height: 56px;
            text: "Ok";
            clicked => {
                root.clicked-ok();
            }
        }

        MyButton {
            width: 120px;
            height: 56px;
            text: "Cancel";
            clicked => {
                root.clicked-cancel();
            }
        }
    }
}

enum SpoolCoreWeightState {
    EntryTabs,
    NewSpoolSelect,
}
export component SpoolCoreWeight inherits Rectangle {
    property <SpoolCoreWeightState> state: SpoolCoreWeightState.EntryTabs;

    background: black;
    select-if-new-spool := SelectIfNewSpool {
        visible: state == SpoolCoreWeightState.NewSpoolSelect;
        cancel-clicked => {
            root.state = SpoolCoreWeightState.EntryTabs;
        }
        no-clicked => {
            AppState.encode-set-core-info(AppState.core-weight-to-encode-after-select-if-new, 0, AppState.core-name-to-encode-after-select-if-new);
            AppState.encoding-spool-core-visible = false;
            root.state = SpoolCoreWeightState.EntryTabs; // for next time
        }
        yes-clicked => {
            AppState.encode-set-core-info(AppState.core-weight-to-encode-after-select-if-new, AppState.spool-scale-weight, AppState.core-name-to-encode-after-select-if-new);
            AppState.encoding-spool-core-visible = false;
            root.state = SpoolCoreWeightState.EntryTabs; // for next time
        }
    }

    VerticalLayout {
        property <bool> show-keyboard;
        visible: state == SpoolCoreWeightState.EntryTabs;
        alignment: stretch;
        Rectangle {
            title := Title {
                text: "Core Weight - " + (tabs.selected-text == "List" ? "Select from List" : tabs.selected-text == "Est" ? "Estimate for New Spool" : tabs.selected-text == "1234" ? "Manually Entered" : "");
                z: 1;
            }

            if tabs.selected-text == "List": MyButton {
                x: root.width - self.width -1px;
                height: title.height;
                width: 57px;
                text: "ABC";
                z: 2;
                clicked => {
                    show-keyboard = true;
                }
            }
        }

        Window {
            HorizontalLayout {
                height: root.height - title.height;
                tabs := LeftTab {
                    height: root.height - title.height;
                    tabs: AppState.spool-scale-state == SpoolScaleState.Loaded ? ["List", "1234", "Est"]  : ["List", "1234"];
                    bottom-tab: "Cancel";
                    botom-tab-pressed => {
                        AppState.encoding-spool-core-visible = false;
                    }
                    width: 70px;
                }

                tab-cards := Window {
                    width: root.width - tabs.width;

                    select-list := Selector {
                        property <string> filter;
                        changed filter => {
                            self.jump-to(0);
                        }
                        selected(text, pos-in-list, id) => {
                            AppState.core-name-to-encode-after-select-if-new = text;
                            AppState.core-weight-to-encode-after-select-if-new = AppBackend.get-spool-core-weight(id);
                            if AppState.spool-scale-state == SpoolScaleState.Loaded {
                              root.state = SpoolCoreWeightState.NewSpoolSelect;
                            } else {
                              AppState.encode-set-core-info(AppState.core-weight-to-encode-after-select-if-new, 0, AppState.core-name-to-encode-after-select-if-new);
                              AppState.encoding-spool-core-visible = false;
                              root.state = SpoolCoreWeightState.EntryTabs; // for next time
                            }
                        }
                        visible: tabs.selected-text == "List";
                        preferred-width: 1000px;
                        option-alignment: left;
                        options-list: AppBackend.get-spools-core-list(filter);
                    }

                    estimate := CoreEstimate {
                        visible: tabs.selected-text == "Est";
                    }

                    type-weight := Rectangle {
                        visible: tabs.selected-text == "1234";
                        background: black;
                        HorizontalLayout {
                            width: root.width - tabs.width;
                            alignment: space-around;
                            NumPad {
                                max-digits: 3;
                                height: tabs.height;
                                ok-clicked => {
                                    AppState.core-name-to-encode-after-select-if-new = "Custom: \{self.number}g";
                                    AppState.core-weight-to-encode-after-select-if-new = self.number;
                                    if AppState.spool-scale-state == SpoolScaleState.Loaded {
                                      root.state = SpoolCoreWeightState.NewSpoolSelect;
                                    } else {
                                      AppState.encode-set-core-info(AppState.core-weight-to-encode-after-select-if-new, 0, AppState.core-name-to-encode-after-select-if-new);
                                      AppState.encoding-spool-core-visible = false;
                                      root.state = SpoolCoreWeightState.EntryTabs; // for next time
                                    }
                                }
                            }
                        }
                    }
                }
            }

            if show-keyboard: Keyboard {
                clicked-ok => {
                    select-list.filter = self.typed-text;
                    show-keyboard = false;
                }
                clicked-cancel => {
                    show-keyboard = false;
                }
            }
        }
    }
}
