import { Title, MyText,MyButton } from "./framework/widgets.slint";
import { AppBackend, AppState, ControlState, UiTray } from "app.slint";
import { Utils } from "utils.slint";

export enum FilamentInfoMode { 
  Encode,
  View
}

export component LabeledText inherits Rectangle {
    in-out property <string> label;
    in-out property <string> text;
    in-out property <color> label-color: blue;
    in-out property <color> text-color: black;
    in-out property <length> label-width;
    HorizontalLayout {
        MyText {
            width: label-width;
            text: label;
            color: label-color;
        }

        MyText {
            text: text;
            color: text-color;
        }
    }
}

export component LabeledInfo inherits LabeledText {
    utils := Utils { }
    label-width: 90px;
}

export component EncodeTitle inherits Title {
    horizontal-alignment: right;
    text: "To Edit, Scan NFC With Phone   ▶ ▶ ▶\u{00A0}";
}

export component ViewTitle inherits Title {
    horizontal-alignment: center;
    text: "Filament Information";
}

export component EncodeButtons inherits HorizontalLayout {
    MyButton {
        horizontal-stretch: 4;
        height: 56px;
        text: "Encode";
        clicked => {
            AppState.control-state = ControlState.Encoding;
            AppState.encode-start();
        }
    }

    MyButton {
        horizontal-stretch: 1;
        height: 56px;
        text: "Cancel";
        clicked => {
            AppState.encode-cancel();
        }
    }
}

export component ViewButtons inherits HorizontalLayout {
    MyButton {
        horizontal-stretch: 1;
        height: 56px;
        text: "Close";
        clicked => {
            AppState.end-show-filament-information();
        }
    }
}

export component FilamentInfo inherits Rectangle {
    in-out property <FilamentInfoMode> mode;
    width: 480px;
    height: 320px;
    background: white;
    property <color> filament-color: AppState.curr-encode-request.tray-index == 999 ? AppState.spool-staging-info.color : AppState.trays-state[AppState.curr-encode-request.tray-index].filament.color;
    utils := Utils { }
    VerticalLayout {
        alignment: stretch;

        if mode == FilamentInfoMode.Encode: EncodeTitle { background: filament-color; text-color: utils.contrasting_color(filament-color); }
        if mode == FilamentInfoMode.View: ViewTitle { background: filament-color; text-color: utils.contrasting_color(filament-color); }

        VerticalLayout {
            alignment: stretch;

            Rectangle {
                border-width: 1px;
                border-color: black;
                VerticalLayout {
                    padding: 10px;
                    spacing: 10px;
                    padding-bottom: 5px;
                    property <string> brand: AppState.curr-encode-request.brand == "" ? "[Unset Brand] " : "\{AppState.curr-encode-request.brand} ";
                    property <string> filament-subtype: AppState.curr-encode-request.filament-subtype == "" ? " [Unset Color]" : " \{AppState.curr-encode-request.filament-subtype}";
                    property <string> color-name: AppState.curr-encode-request.color-name == "" ? "" : " \{AppState.curr-encode-request.color-name} ";
                    MyText {
                        horizontal-alignment: center;
                        text: "\{brand}\{AppState.curr-encode-request-display.filament-type}\{filament-subtype}\{color-name}";
                    }

                    LabeledInfo {
                        label: "Note:";
                        text: AppState.curr-encode-request.note;
                    }
                }
            }

            Rectangle {
                border-width: 1px;
                border-color: black;
                VerticalLayout {
                    padding: 10px;
                    spacing: 10px;
                    LabeledInfo {
                        label: "In Slicer:";
                        text: AppState.curr-encode-request-display.slicer-name;
                    }

                    HorizontalLayout {
                        alignment: space-between;
                        LabeledInfo {
                            horizontal-stretch: 1;
                            label: "Color";
                            text: "\{AppState.curr-encode-request-display.color-code}";
                        }

                        LabeledInfo {
                            label: "Temps: ";
                            text: "\{AppState.curr-encode-request-display.temp-min}°C - \{AppState.curr-encode-request-display.temp-max}°C";
                        }
                    }

                    VerticalLayout {
                        LabeledInfo {
                            label: "PA(K):";
                            text: AppState.curr-encode-request-display.pa-line1;
                        }

                        LabeledInfo {
                            label: "";
                            text: AppState.curr-encode-request-display.pa-line2;
                        }
                    }

                    LabeledInfo {
                        property <string> core: AppState.curr-encode-request.weight-core != 0 ? "\{AppState.curr-encode-request.weight-core}g" : "—";
                        property <string> new: AppState.curr-encode-request.weight-new != 0 ? "\{AppState.curr-encode-request.weight-new}g" : "—";
                        label: "Weights:";
                        text: "\{core} (Core) / \{new} (New)";
                    }
                }
            }
        }

        if mode == FilamentInfoMode.Encode: EncodeButtons {}
        if mode == FilamentInfoMode.View: ViewButtons {}
    }
}
