[package]
edition = "2021"
name    = "SpoolEaseScale"
version = "0.3.1"

[patch.crates-io]
bitvec = { git = "https://github.com/arctic-alpaca/ferrilab" }
radium = { git = "https://github.com/arctic-alpaca/ferrilab" }

[dependencies]
esp-alloc = { version = "0.6.0" }
esp-backtrace = { version = "0.15.0", features = [ "esp32s3", "exception-handler", "panic-handler", "println", ] }
esp-hal = { version = "0.23.1", features = ["esp32s3", "unstable", "octal-psram"] }
esp-println = { version = "0.13.0", default-features = false, features = ["critical-section", "colors", "auto", "log"] }
esp-wifi = { version = "0.12.0", features = [ "wifi", "utils", "esp-alloc", "log"] }
esp-hal-embassy = { version = "0.6.0", features = ["esp32s3"] }
esp-mbedtls = { git = "https://github.com/esp-rs/esp-mbedtls.git", features = [ "async" ], rev = "1806f8f622b08a9b54de91814eea13c6b3d9ff1c" }
esp-hal-ota = { version = "0.3.2" }
esp-storage = { version = "0.4.0", features = [ "nor-flash", "esp32s3" ] }
embedded-hal-bus = { version = "0.2.0", features = ["async"] }


embassy-executor = { version = "0.7.0", features = ["task-arena-size-20480"] }
embassy-net = { version = "0.6.0", features = [ "tcp", "udp", "dhcpv4", "medium-ethernet", "multicast" ] }
embassy-futures = { version = "0.1.1" }
embassy-time = { version = "0.4.0", features = ["generic-queue-8"] }
embassy-embedded-hal = { version = "0.3.0" }
embassy-sync = { version = "0.6.2" }

sequential-storage = { git = "https://github.com/tweedegolf/sequential-storage", features = [ "alloc", ], rev = "b6f7da77b7f3d66bc1ac36992a6a7b399b5ba030" }

critical-section = "1.2.0"
once_cell = { version = "1.20.2", default-features = false, features = ["alloc"] }
picoserve = {version = "0.15.1", features = ["alloc", "embassy"] }
log = { version = "0.4.21" }
static_cell = { version = "2.1.0", features = ["nightly"] }
rand = { version = "0.8", default-features = false }

serde = { version = "1.0.213", default-features = false, features = [ "derive", "alloc", ] }
serde_json = { version = "1.0.132", default-features = false, features = [ "alloc", ] }

# framework = { package = "esp-hal-app-framework", git = "https://github.com/yanshay/esp-hal-app/", tag = "v0.2.1", features = ["esp32s3", "improv-jtag-serial"] }
framework = { package = "esp-hal-app-framework", path = "../../esp-hal-app/esp-hal-app-framework/", features = ["esp32s3", "improv-jtag-serial"] }

getrandom = { version = "0.2.15", features = ["custom"] }

loadcell = { version = "0.3.0" }
hx711_spi = { version = "0.7.0" } #, features = ["invert-sdo"]}
num-traits = { version = "0.2.19", default-features = false }

shared = { path = "../shared/" }

esp-hal-smartled = { git = "https://github.com/esp-rs/esp-hal-community", rev = "ad75112"}
smart-leds = "0.4.0"


[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false



[features]
default = ["esp32s3"]
esp32s3 = [
  "esp-hal/esp32s3",
  "esp-backtrace/esp32s3",
  "esp-println/esp32s3",
  "esp-wifi/esp32s3",
  "esp-mbedtls/esp32s3",
  "esp-hal-embassy/esp32s3",
  "esp-storage/esp32s3",
  "esp-hal-ota/esp32s3",
  "getrandom/custom"
]
