export enum OtaState {
  NotStarted,
  Checking,
  UserInput,
  Started,
  Completed,
  Failed
}

export enum ResetWifiCredentialsState {
  NotStarted,
  UserInput
}

export enum ResetFixedSecurityKeyState {
  NotStarted,
  UserInput
}

export enum RestartDeviceState {
  NotStarted,
  UserInput
}

//TODO: Think if to simplify now that WebConfig is always on, either STA or AP (test that AP wasn't hurt by changes)
export enum WebConfigState {
  Stopped,
  Starting,
  Started-AP,
  Started-STA,
  Started-STA-Displayed,
  Stopping,
}

export global FrameworkBackend {
    callback reset-flash-wifi-credentials();
    callback reset-fixed-security-key();
    callback start-web-config();
    callback stop-web-config();
    callback reset-device();
    callback update-firmware-ota();
    callback term-info(string);
    pure callback info(string);
    pure callback debug(string);
}

export global Log {
    public function term-info(text: string) {
        FrameworkBackend.info(text);
        FrameworkBackend.term-info("\n\{text}");
    }
    pure public function info(text: string) {
        FrameworkBackend.info(text);
    }
    pure public function debug(text: string) {
        FrameworkBackend.debug(text);
    }
}

struct AppInfo {
    name: string,
    version: string,
}

struct OtaInfo {
    version: string,
    newer: bool
}

export global FrameworkState {
    in-out property <length> display-width: 800px;
    in-out property <length> display-height: 480px;
    out property <length> swipe-y-length: display-height == 800px ? 40px : 40px;
    out property <length> swipe-x-length: display-width == 480px ? 96px : 96px;

    in-out property <AppInfo> app-info: { name: "AppName", version: "?.?.?" };
    // in-out property <string> term-text: "Initializing...";
    in-out property <string> term-text;
    in-out property <string> term-text-added;

    in-out property <WebConfigState> web-config-state: WebConfigState.Stopped;
    in-out property <string> web-config-url: "Initializing ...";
    in-out property <string> web-config-ssid: "Initializing ...";
    in-out property <string> web-config-key: "";

    in-out property <OtaState> ota-state: OtaState.NotStarted;
    in-out property <bool> ota-allow-close-during-update: false;
    in-out property <ResetWifiCredentialsState> reset-wifi-credentials-state: ResetWifiCredentialsState.NotStarted;
    in-out property <ResetFixedSecurityKeyState> reset-fixed-security-key-state: ResetFixedSecurityKeyState.NotStarted;
    in-out property <RestartDeviceState> restart-device-state: RestartDeviceState.NotStarted;
    in-out property <string> ota-message: "";
    out property <OtaInfo> ota-info: { version: "Unknown", newer: false };

    // Public Functions called from backend to alter state

    // Terminal 

    // public function add-term-text(line: string) {
    //     term-text = term-text + line;
    // }

    // Ota

    public function set-ota-info(ota-info: OtaInfo) {
        self.ota-info = ota-info;
      // potentially trigger notification
    }
    public function ota-started() {
        self.ota-state = OtaState.Started;
        self.ota-message = "Started Firmware Update";
    }
    public function ota-status(text: string) {
        self.ota-message = text;
    }
    public function ota-completed(text: string) {
        if self.ota-state != OtaState.NotStarted {
            self.ota-state = OtaState.Completed;
        }
        self.ota-message = text;
    }
    public function ota-failed(text: string) {
        if self.ota-state != OtaState.NotStarted {
            self.ota-state = OtaState.Failed;
        }
        self.ota-message = text;
    }
    public function ota-clear-message() {
        self.ota-message = "";
    }

    // Web Config

    public function set-web-config-url(url: string, ssid: string) {
        self.web-config-url = url;
        self.web-config-ssid = ssid;
    }
    public function web-config-started(key: string, mode: WebConfigState) {
        self.web-config-key = key;
        self.web-config-state = mode;
    }
    public function web-config-stopped() {
        self.web-config-key = "";
        self.web-config-state = WebConfigState.Stopped;
    }
}
