import { ScrollView } from "std-widgets.slint";
import { FrameworkState } from "framework.slint";
import { MyButton } from "widgets.slint";

// export component Terminal inherits Rectangle {
//     scroller := ScrollView {
//         height: root.height;
//         width: root.width;
//         viewport-height: child-text.height + 40px;
//         viewport-width: child-text.width;
//         child-text := Text {
//             width: parent.width - 10px;
//             wrap: char-wrap;
//             vertical-alignment: bottom;
//             font-size: 20px;
//             color: white;
//             text: FrameworkState.term-text;
//             changed text => {
//                 scroller.viewport-y = root.height - child-text.height - 36px;
//             }
//         }
//     }
//
//     up-button := MyButton {
//         x: root.width - self.width + 1px;
//         y: -1px;
//         text: "▲";
//         width: 40px;
//         height: 40px;
//         clicked => {
//             scroller.viewport-y = scroller.viewport-y + 22px;
//         }
//     }
//
//     down-button := MyButton {
//         x: root.width - self.width + 1px;
//         y: root.height - self.height;
//         text: "▼";
//         width: 40px;
//         height: 40px;
//         clicked => {
//             scroller.viewport-y = scroller.viewport-y - 22px;
//         }
//     }
// }


export component Terminal inherits Rectangle {
    public function reset-scroll() {
        self.locked-offset = 0;
        self.scroll-offset-from-end = 0;
    }
    public function is-scrolled() -> bool {
      return scroll-offset-from-end != 0;
    }
    // width: 480px;
    // height: 320px;
    in-out property <string> text: "Hello"; // FrameworkState.new-term-text;
    in-out property <length> scroll-offset-from-end: 0;
    property <length> offset-for-end: Math.max(txt.height - self.height, 0px);
    in-out property <length> locked-offset;
    property <length> previous-height;
    property <bool> dummy: false;
    txt-added := Text { // for calculating dimensions of added text, must be same properties as txt
        width: root.width - 40px;
        font-size: 20px;
        wrap: char-wrap;
        y: -200px;
        x: root.x;
        visible: false;
        text: FrameworkState.term-text-added;
        color: #00000000;
    }

    txt := Text {
        width: root.width - 40px;
        font-size: 20px;
        wrap: char-wrap;
        changed text => {
            if scroll-offset-from-end != 0 {
                locked-offset = locked-offset - (previous-height - self.height );
                scroll-offset-from-end = scroll-offset-from-end + txt-added.height;
            }
            previous-height = self.height;
        }
        y: scroll-offset-from-end == 0 ? -offset-for-end : -locked-offset + scroll-offset-from-end;
        x: root.x;
        horizontal-alignment: left;
        vertical-alignment: top;
        color: white;
        text: root.text;
    }

    up-button := MyButton {
        x: root.width - self.width + 1px;
        y: -1px;
        text: "▲";
        width: 40px;
        height: 40px;
        clicked => {
            if scroll-offset-from-end == 0 {
                locked-offset = offset-for-end;
            }
            scroll-offset-from-end = scroll-offset-from-end + 22px;
        }
    }

    down-button := MyButton {
        x: root.width - self.width + 1px;
        y: root.height - 2*self.height;
        text: "▼";
        width: 40px;
        height: 40px;
        clicked => {
            if scroll-offset-from-end > 0px {
                scroll-offset-from-end = scroll-offset-from-end - 22px;
                
            }
        }
    }

    end-button := MyButton {
        x: root.width - self.width + 1px;
        y: root.height - 1*self.height;
        text: "■"; // "▼";
        width: 40px;
        height: 40px;
        clicked => {
            if scroll-offset-from-end > 0px {
                scroll-offset-from-end = 0;
            }
        }
    }

    // MyButton {
    //     text: "Add";
    //     width: 80px;
    //     height: 56px;
    //     x: 300px;
    //     y: 100px;
    //     clicked => {
    //         FrameworkState.new-term-text = FrameworkState.new-term-text + "\nAdded Line";
    //         FrameworkState.new-term-text-added = "Added Line";
    //     }
    // }

    // Rectangle {
    //     background: white;
    //     x: 300px;
    //     y: 160px;
    //     width: 180px;
    //     height: 120px;
    //     Text {
    //         width: parent.width;
    //         height: parent.height;
    //         color: black;
    //         text: "txt.height: \{txt.height / 1px}\noffset: \{offset-for-end / 1px}\nlocked-off:\{locked-offset / 1px}\nscroll-offset:\{scroll-offset-from-end/1px}\ntxt-add:\{txt-added.height/1px}";
    //         font-size: 20px;
    //     }
    // }
}
