import { MyButton, Title } from "framework/widgets.slint";
import { SettingsButton } from "framework/settings.slint";
import { ScaleCalibration } from "scale-calibration.slint";
import { AppBackend, AppState, SpoolScaleState } from "app.slint";
import { Settings } from "framework/settings.slint";

enum AppSettingsState {
  Buttons,
  ScaleCalibration,
}

export component AppSettings inherits Settings {
    callback done;
    property <AppSettingsState> state: Buttons;
    tabs: ["1", "2"];

    framework-tab-selected: self.selected-tab == 0;

    if self.selected-tab == 1 && state == AppSettingsState.Buttons: VerticalLayout {
        x: parent.x-offset;
        y: parent.y-offset;
        width: parent.buttons-width;

        SettingsButton {
            text: "Calibrate Scale";
            enabled: !(AppState.spool-scale-state == SpoolScaleState.Unknown || AppState.spool-scale-state == SpoolScaleState.Disconnected);
            clicked => {
                root.state = AppSettingsState.ScaleCalibration;
            }
        }

        SettingsButton {
            text: "Erase Previously Used Spools List";
            clicked => {
                AppBackend.erase-previously-used-core-list();
            }
        }
    }

    if state == AppSettingsState.ScaleCalibration: ScaleCalibration {
        cancel-clicked => {
            root.state = AppSettingsState.Buttons;
        }
        ok-clicked => {
            root.state = AppSettingsState.Buttons;
            // done();
        }
    }
}
