import { FrameworkState } from "framework/framework.slint";
import { SelectorOption } from "framework/widgets.slint";
import { SelectorOptionsList } from "framework/widgets.slint";
// Types

export enum UiTrayState { Unknown, Empty, Spool, Reading, Ready, Loading, Unloading, Loaded }
// Spool - Spool entered the slot but not yet processed by AMS, so not ready yet
// Ready - there is a spool, it is not loaded to the extruder now
// Loading - during the process of loading into the extruder
// Loaded - in the extruder
// Unloading - during the process of unloading from the extruder
export enum UiFilamentState { Unknown, Known }

export struct UiFilament {
  state: UiFilamentState,
  color: color,
  material: string,
}

export struct UiTray {
  id: int,
  external: bool,
  spool-state: UiTrayState,
  filament: UiFilament,
  k: string,
  tagged: bool,
}

export struct UiSpoolInfo {
  color: color,
  material: string,
  k: string,
  weight-core: int,
}

// Consts

export global AppConsts {
    out property <length> trays-spacing: 4px;
    out property <length> external-tray-separator: 2px;
    out property <brush> no-color: @linear-gradient(45deg, #fff 0%, #333 100%);
    out property <brush> title-gradient: @linear-gradient(180deg, #09009B 0%, #0000CA 39%, #001dff 100%);
    // out property <brush> no-color: @linear-gradient(45deg, #fff 0%, #AAA 54%, #333 100%);
    // out property <brush> no-color: @linear-gradient(180deg, #fff 0%, #666 50%, #333 100%);
}

export enum ControlState {
  Booting,
  ConnectingToPrinter ,
  BootFailed,
  Ready,
  EncodeSelectSource,
  EncodeSetSpoolCore,
  StagingSelected,
  Encoding,
  Reading,
  PostAction,
}

export enum SpoolScaleState {
  Unknown,
  Uncalibrated,
  Disconnected,
  Connected,
  Empty,
  Loaded,
}

export enum StatusType {
  Normal,
  Success,
  Error
}

export enum SpoolStagingState {
  Empty,
  Loaded,
}

// Functions to call rust
export global AppBackend {
    callback clear-staging();
    callback set-staging-to-tray(tray-id: int);
    callback encode-tray-to-tag(tray-id: int, weight-core: int, weight-new: int, core-name: string) -> int; // returns how long it will try to encode, for timer
    callback read-tag-mode();
    callback reset-printer();
    callback select-printer(printer: string);
    callback calibrate-scale(weight: int);
    callback erase-previously-used-core-list();
    pure callback get-spools-core-list(filter: string)-> [SelectorOption];
    callback get-spool-core-weight(id: int) -> int;
}

export global AppState {
    in-out property <bool> select-printer: false;
    in-out property <ControlState> control-state: ControlState.Booting;

    in-out property <SpoolStagingState> spool-staging-state: SpoolStagingState.Empty;
    in-out property <UiSpoolInfo> spool-staging-info;
    in-out property <int> staging-to-tray: -1; // tray that needs to be updated with filament when recognizing on backend tray is reading

    in-out property <string> user-message: "Booting ...";
    in-out property <StatusType> user-message-type: StatusType.Normal;
    in-out property <int> encode-timeout: 999;

    in-out property <int> curr-ams-id: 0;
    in-out property <[int]> ams-exists: [0];

    in-out property <string> curr-printer: "";
    in-out property <[string]> available-printers: [];
    in-out property <string> default-printer: "";
    in-out property <string> pending-curr-printer: "";
    changed pending-curr-printer => {
      if pending-curr-printer != "" {
        AppBackend.select-printer(pending-curr-printer);
        pending-curr-printer = "";
      }
    }

    in-out property <SpoolScaleState> spool-scale-state: SpoolScaleState.Unknown;
    in-out property <int> spool-scale-weight: 0;
    in-out property <bool> spool-scale-weight-stable: false;
    in-out property <int> spool-scale-raw-data: 0;
    in-out property <bool> spool-scale-flash: false;
    in-out property <SpoolScaleState> spool-scale-after-flash-state: SpoolScaleState.Unknown;
    in-out property <int> tray_id_to_encode_after_setting_core_weight: -1;
    in-out property <int> core-weight-to-encode-after-select-if-new: 0;
    in-out property <string> core-name-to-encode-after-select-if-new;

    in-out property <bool> highlight-trays: false;
    in-out property <bool> highlight-staging: false;
    in-out property <int> highlight-tray: -1;
    in-out property <bool> highlight-tray-flash: false;
       out property <int> highlight-tray-counter-length: 20;
    in-out property <int> highlight-tray-counter: highlight-tray-counter-length;

    public function start-highlight-tray(tray-id: int) {
        self.highlight-tray = tray-id;
        self.highlight-tray-counter = highlight-tray-counter-length;
    }
    public function start-highlight-tray-forever(tray-id: int) {
        self.highlight-tray = tray-id;
        self.highlight-tray-counter = -1; // number even/odd to sync this tray flashing with other flashings
    }
    public function stop-highlight-tray() {
        AppState.highlight-tray = -1;
        AppState.highlight-tray-flash = false;
        AppState.highlight-tray-counter = AppState.highlight-tray-counter-length;
    }

// Functions called locally fom Rust

    public function printer-connected(printer-name: string) {
        if self.control-state == ControlState.Booting || self.control-state == ControlState.ConnectingToPrinter {
            self.control-state = ControlState.Ready;
        }
    }

    public function boot-failed(status: string) {
        self.control-state = ControlState.BootFailed;
        self.user-message = status;
        self.user-message-type = StatusType.Error;
    }

    public function read-tag-found() {
        if self.control-state == ControlState.Ready {
            self.control-state = ControlState.Reading;
            self.user-message = "Tag to Read Found,\nReading ...";
            self.user-message-type = StatusType.Normal;
        }
    }
    public function read-tag-failed(err-txt: string) {
        if self.control-state == ControlState.Reading {
            self.control-state = ControlState.PostAction;
            self.user-message = "Scanning Tag Failed\n\{err-txt}";
            self.user-message-type = StatusType.Error;
        }
    }
    public function read-tag-succeeded(ui-spool-info: UiSpoolInfo) {
        self.spool-staging-state = SpoolStagingState.Loaded;
        self.spool-staging-info = ui-spool-info;
        self.control-state = ControlState.PostAction;
        self.user-message = "Tag Scanned to Staging";
        self.user-message-type = StatusType.Success;
        start-highlight-tray(999);
    }

    public function update-spool-staging(ui-spool-info: UiSpoolInfo) {
        self.spool-staging-state = SpoolStagingState.Loaded;
        self.spool-staging-info = ui-spool-info;
        start-highlight-tray(999);
    }

    public function empty-spool-staging() {
        self.spool-staging-state = SpoolStagingState.Empty;
        self.spool-staging-info.weight-core = 0;
    }

    public function encode-tag-found() {
        self.control-state = ControlState.Encoding;
        self.user-message = "Tag to Encode Found,\nEncoding ...";
        self.user-message-type = StatusType.Normal;
    }
    // Called from UI in case of UI timeout, can also be called from backend for timeout case
    public function encoding-timeout() {
        self.control-state = ControlState.PostAction;
        self.user-message = "Encoding Tag Timed Out";
        self.user-message-type = StatusType.Error
    }

    public function encoding-failed(err-txt: string) {
        if self.control-state == ControlState.Reading {
            self.control-state = ControlState.PostAction;
            self.user-message = "Encoding Tag Failed\n\{err-txt}";
            self.user-message-type = StatusType.Error;
        }
    }
    public function encoding-succeeded(ams-id: int, tray-id: int) {
      // 254 - External Tray
      // 999 - Staging
        self.control-state = ControlState.PostAction;
        self.user-message = (tray-id == 999 ? "Encoding\nStaging Filament\nSucceeded" : tray-id == 254 ? "Encoding\nExternal Tray Filament\nSucceeded" : "Encoding\nAMS \{ams-id + 1}, Slot \{tray-id + 1} Filament\nSucceeded");
        self.user-message-type = StatusType.Success;
        self.stop-highlight-tray();
    }

    public function tray-update-failed(ams-id: int, tray-id: int, err-txt: string) {
        self.control-state = ControlState.PostAction;
        self.user-message = (tray-id == 254 ? "Configuring\nExternal Spool Filament\nFailed" : "Configuring\nAMS \{ams-id + 1}, Slot \{tray-id + 1} Filament\nFailed");
        self.user-message-type = StatusType.Error;
    }
    public function tray-update-succeeded(printer: string, ams-id: int, tray-id: int) {
        self.control-state = ControlState.PostAction;
        self.user-message = (tray-id == 254 ? "Configuring\nExternal Spool Filament\nSucceeded" : "Configuring\nAMS \{ams-id + 1}, Slot \{tray-id + 1} Filament\nSucceeded");
        self.user-message-type = StatusType.Success;
        start-highlight-tray((tray-id == 254) ? 254 : tray-id + ams-id * 4);
        if printer != self.curr-printer {
          self.set-later-curr-printer(printer)
        }
    }

    public function encode-start(tray-id: int, weight-core: int, weight-new: int, core-name: string) {
        self.encode-timeout = AppBackend.encode-tray-to-tag(tray-id, weight-core, weight-new, core-name);
        AppState.start-highlight-tray-forever(tray-id);
        self.control-state = ControlState.Encoding;
        user-message = "Place Spool Tag to Encode";
        user-message-type = StatusType.Normal;
    }

    public function new_single_tray_loading(tray_id: int) {
        if self.spool-staging-state == SpoolStagingState.Loaded {
            self.staging-to-tray = tray_id;
        }
    }

    public function spool-scale-connected() {
        self.spool-scale-state = SpoolScaleState.Connected;
        self.spool-scale-flash = true;
        self.spool-scale-after-flash-state = SpoolScaleState.Empty;

    }

    public function spool-scale-disconnected() {
        self.spool-scale-state = SpoolScaleState.Disconnected;
        self.spool-scale-flash = false;
        self.spool-scale-after-flash-state = SpoolScaleState.Disconnected;
    }

    public function spool-scale-uncalibrated() {
        self.spool-scale-state = SpoolScaleState.Uncalibrated;
        self.spool-scale-flash = false;
        self.spool-scale-after-flash-state = SpoolScaleState.Uncalibrated;
    }

    public function spool-scale-loaded(weight: int, stable: bool) {
        self.spool-scale-state = SpoolScaleState.Loaded;
        self.spool-scale-weight = weight;
        self.spool-scale-weight-stable = stable;
        self.spool-scale-flash = true;
        self.spool-scale-after-flash-state = SpoolScaleState.Loaded;
        // if started with simple encoding, and then loaded a spool on the scale
        // interpret this as asking to encode also weight
        if AppState.control-state == ControlState.Encoding {
            AppBackend.read-tag-mode();
            AppState.stop-highlight-tray();
            AppState.control-state = ControlState.EncodeSetSpoolCore
        }
    }

    public function spool-scale-load-changed(weight: int, stable: bool) {
        self.spool-scale-weight = weight;
        self.spool-scale-weight-stable = stable;
    }

    public function spool-scale-load-removed() {
        self.spool-scale-state = SpoolScaleState.Empty;
        self.spool-scale-weight = 0;
        self.spool-scale-weight-stable = false;
        self.spool-scale-flash = false;
        self.spool-scale-after-flash-state = SpoolScaleState.Empty;
    }
    public function spool_scale_raw_samples_avg(raw-data: int) {
        self.spool-scale-raw-data = raw-data;
    }

    in-out property <[UiTray]> trays-state: self.empty-trays-state();

    public function set-printers-info(available-printers: [string], default_printer: string) {
        self.available-printers = available-printers;
        self.default-printer = default-printer;
    }

    public function set-curr-printer(curr-printer: string) {
        self.curr-printer = curr_printer;
    }
    // the below is a function to call with delay the select-printer
    // to avoid rust's borrowing issues in the implementation
    // uses property changed for delayed call
    public function set-later-curr-printer(curr-printer: string) {
        self.pending-curr-printer = curr-printer
    }

    public function reset-printer() {
        self.curr-ams-id = 0;
        self.ams-exists = [0];
        self.trays-state = self.empty-trays-state();
        self.control-state = ControlState.ConnectingToPrinter;
    }

    function empty-trays-state() -> [UiTray] {
        return [
  // External
        {
                id: 254,
                external: true,
                spool-state: UiTrayState.Unknown,
                filament: {
                    state: UiFilamentState.Unknown,
                    color: #000,
                    material: "???",
                },
                workflowState: {
                    during_encode: false,
                    during_scan: false,
                },
                k: -1.0,
                tagged: false,
            },

  // AMS: 0
        {
                id: 0,
                external: false,
                spool-state: UiTrayState.Unknown,
                filament: {
                    state: UiFilamentState.Unknown,
                    color: #000,
                    material: "???",
                },
                workflowState: {
                    during_encode: false,
                    during_scan: false,
                },
                k: -1.0,
                tagged: false,
            },
            {
                id: 1,
                external: false,
                spool-state: UiTrayState.Unknown,
                filament: {
                    state: UiFilamentState.Unknown,
                    color: #000,
                    material: "???",
                },
                workflowState: {
                    during_encode: false,
                    during_scan: false,
                },
                k: -1.0,
                tagged: false,
            },
            {
                id: 2,
                external: false,
                spool-state: UiTrayState.Unknown,
                filament: {
                    state: UiFilamentState.Unknown,
                    color: #000,
                    material: "???",
                },
                workflowState: {
                    during_encode: false,
                    during_scan: false,
                },
                k: -1.0,
                tagged: false,
            },
            {
                id: 3,
                external: false,
                spool-state: UiTrayState.Unknown,
                filament: {
                    state: UiFilamentState.Unknown,
                    color: #000,
                    material: "???",
                },
                workflowState: {
                    during_encode: false,
                    during_scan: false,
                },
                k: -1.0,
                tagged: false,
            },

  // AMS 1
        {
                id: 4,
                external: false,
                spool-state: UiTrayState.Unknown,
                filament: {
                    state: UiFilamentState.Unknown,
                    color: #000,
                    material: "???",
                },
                workflowState: {
                    during_encode: false,
                    during_scan: false,
                },
                k: -1.0,
                tagged: false,
            },
            {
                id: 5,
                external: false,
                spool-state: UiTrayState.Unknown,
                filament: {
                    state: UiFilamentState.Unknown,
                    color: #000,
                    material: "???",
                },
                workflowState: {
                    during_encode: false,
                    during_scan: false,
                },
                k: -1.0,
                tagged: false,
            },
            {
                id: 6,
                external: false,
                spool-state: UiTrayState.Unknown,
                filament: {
                    state: UiFilamentState.Unknown,
                    color: #000,
                    material: "???",
                },
                workflowState: {
                    during_encode: false,
                    during_scan: false,
                },
                k: -1.0,
                tagged: false,
            },
            {
                id: 7,
                external: false,
                spool-state: UiTrayState.Unknown,
                filament: {
                    state: UiFilamentState.Unknown,
                    color: #000,
                    material: "???",
                },
                workflowState: {
                    during_encode: false,
                    during_scan: false,
                },
                k: -1.0,
                tagged: false,
            },
  // AMS 2
        {
                id: 8,
                external: false,
                spool-state: UiTrayState.Unknown,
                filament: {
                    state: UiFilamentState.Unknown,
                    color: #000,
                    material: "???",
                },
                workflowState: {
                    during_encode: false,
                    during_scan: false,
                },
                k: -1.0,
                tagged: false,
            },
            {
                id: 9,
                external: false,
                spool-state: UiTrayState.Unknown,
                filament: {
                    state: UiFilamentState.Unknown,
                    color: #000,
                    material: "???",
                },
                workflowState: {
                    during_encode: false,
                    during_scan: false,
                },
                k: -1.0,
                tagged: false,
            },
            {
                id: 10,
                external: false,
                spool-state: UiTrayState.Unknown,
                filament: {
                    state: UiFilamentState.Unknown,
                    color: #000,
                    material: "???",
                },
                workflowState: {
                    during_encode: false,
                    during_scan: false,
                },
                k: -1.0,
                tagged: false,
            },
            {
                id: 11,
                external: false,
                spool-state: UiTrayState.Unknown,
                filament: {
                    state: UiFilamentState.Unknown,
                    color: #000,
                    material: "???",
                },
                workflowState: {
                    during_encode: false,
                    during_scan: false,
                },
                k: -1.0,
                tagged: false,
            },
  // AMS 3
        {
                id: 12,
                external: false,
                spool-state: UiTrayState.Unknown,
                filament: {
                    state: UiFilamentState.Unknown,
                    color: #000,
                    material: "???",
                },
                workflowState: {
                    during_encode: false,
                    during_scan: false,
                },
                k: -1.0,
                tagged: false,
            },
            {
                id: 13,
                external: false,
                spool-state: UiTrayState.Unknown,
                filament: {
                    state: UiFilamentState.Unknown,
                    color: #000,
                    material: "???",
                },
                workflowState: {
                    during_encode: false,
                    during_scan: false,
                },
                k: -1.0,
                tagged: false,
            },
            {
                id: 14,
                external: false,
                spool-state: UiTrayState.Unknown,
                filament: {
                    state: UiFilamentState.Unknown,
                    color: #000,
                    material: "???",
                },
                workflowState: {
                    during_encode: false,
                    during_scan: false,
                },
                k: -1.0,
                tagged: false,
            },
            {
                id: 15,
                external: false,
                spool-state: UiTrayState.Unknown,
                filament: {
                    state: UiFilamentState.Unknown,
                    color: #000,
                    material: "???",
                },
                workflowState: {
                    during_encode: false,
                    during_scan: false,
                },
                k: -1.0,
                tagged: false,
            },
        ];
    }

}
