[package]
name = "shared"
version = "0.5.5"
edition = "2024"

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
opt-level = 's'
lto = 'fat'
overflow-checks = false

# DON'T REMOVE ANY COMMENTED LINES IN THIS FILE !!!

[dependencies]
serde = { version = "1.0.213", default-features = false, features = [ "derive", "alloc", ] }
serde_json = { version = "1.0.132", default-features = false, features = [ "alloc", ] }
serde_with = { version = "3.16.0", default-features = false, features = ["alloc", "macros", "base64", "hashbrown_0_16", "hex"]}


framework = { package = "esp-hal-app-framework", path = "../../../esp-hal-app/esp-hal-app-framework/", default-features = false, features = ["esp32s3"] }
# framework = { package = "esp-hal-app-framework", git = "https://github.com/yanshay/esp-hal-app/", tag = "0.6.8", features = ["esp32s3"] }
pn532 = { git = "https://github.com/yanshay/pn532", branch ="yanshay_esp-hal-1.0.0-upgrade", default-features = false }
# pn532 = { path = "../../../../../../OpenSourceProj/forked/pn532/", default-features = false }
embassy-time = { version = "0.5.0", features = ["generic-queue-8"] }
embassy-net = { version = "0.8.0", features = [ "raw", "tcp", "udp", "dhcpv4", "dns", "medium-ethernet", "multicast" ] }
esp-hal = { version = "1.0.0", features = ["unstable"] }
embassy-sync = { version = "0.7.2" }
no_std_io = { version = "0.6.0", default-features = false, features = [ "alloc" ] }
log = { version = "0.4.22", features = ["serde"] }
static_cell = { version = "2.1", features = ["nightly"] }
base64 = { version = "0.22.1", default-features = false, features = ["alloc"] }
embassy-futures = { version = "0.1.2" }
embedded-hal-bus = { version = "0.3.0", features = ["async"] }
embassy-executor = { version = "0.9.0", features = ["nightly"] }
getrandom = { version = "0.2.15", features = ["custom"] }
hashbrown = { version = "0.16.1", features = ["serde"] }
snafu = { git = "https://github.com/shepmaster/snafu", rev = "aedc9db8c04a437b4c547efd4d73e9337fa43a4a", default-features = false, features = ["rust_1_81", "alloc"]} # , "backtraces-impl-backtrace-crate"]} 
# esp-mbedtls = { package = "mbedtls-rs", path = "../../../../../../OpenSourceProj/forked/mbedtls-rs/mbedtls-rs", features = [ "log" ] }
esp-mbedtls = { package = "mbedtls-rs", git = "https://github.com/esp-rs/mbedtls-rs", features = [ "log" ] }
esp-alloc = { version = "0.9.0" }
miniz_oxide = { version = "0.8.9", default-features = false }
url = {version = "2.5.4", default-features = false}
edge-nal-embassy = "0.8.1"
edge-nal = { version = "0.6.0" }
edge-http = { version = "0.7.0" }
embedded-io-async = { version = "0.7" }
serde-csv-core = "0.3.2"
hex = {version = "0.4.3", default-features = false, features = ["alloc"]}

# ndef-rs = { path = "../../../../../../OpenSourceProj/forked/ndef-rs/ndef", default-features = false}
ndef-rs = { git = "https://github.com/yanshay/ndef-rs" , branch = "yanshay_no_std", default-features = false}

# crypo for bambu/mifare
sha2 = { version = "0.10.8", default-features = false}
hmac = { version = "0.12.1", default-features = false}

[features]
default = ["esp32s3"]

esp32s3 = [
  "esp-hal/esp32s3",
]
