import { MyText, MyButton, Title } from "framework/widgets.slint";
import { SettingsButton } from "framework/settings.slint";
import { ScaleCalibration } from "scale-calibration.slint";
import { AppBackend, AppState, SpoolScaleState } from "app.slint";
import { Settings } from "framework/settings.slint";

enum AppSettingsState {
  Buttons,
  ScaleCalibration,
  ScalesInformation,
}

export component ScalesInformation inherits Rectangle {
    callback clicked;
    property <string> remote-scale-info: AppBackend.get-connected-scale-info();

    background: white;
    VerticalLayout {
        alignment: space-between;
        VerticalLayout {
            alignment: start;
            title := Title {
                width: root.width;
                text: !AppState.remote-scale-configured ? "Remote Scale Not Available" : root.remote-scale-info == "<No Remote Scale Connected>" ? "Trying to Connect to Remote Scale" : "Remote Scale Connected";
            }

            MyText {
                x: 10px;
                vertical-alignment: center;
                width: root.width - self.x * 2;
                height: title.height;
                text: root.remote-scale-info;
            }

            Title {
                width: root.width;
                text: "Scales on Network (close & reopen to update)";
            }

            for scale in AppBackend.get-available-scales-info(): MyText {
                x: 10px;
                vertical-alignment: center;
                width: root.width - self.x * 2;
                height: 30px;
                text: scale;
            }
        }

        VerticalLayout {
            MyText {
                x: 10px;
                width: root.width - self.x * 2;
                height: 54px;
                vertical-alignment: center;
                wrap: word-wrap;
                text: "Note: To connect a scale from this list, configure its name or IP in the Console Web Config.";
            }

            MyButton {
                clicked => {
                    root.clicked()
                }
                width: root.width;
                height: 56px;
                text: "Ok";
            }
        }
    }
}

export component AppSettings inherits Settings {
    callback done;
    property <AppSettingsState> state: Buttons;
    tabs: ["1", "2"];

    framework-tab-selected: self.selected-tab == 0;

    if self.selected-tab == 1 && state == AppSettingsState.Buttons: VerticalLayout {
        x: parent.x-offset;
        y: parent.y-offset;
        width: parent.buttons-width;

        SettingsButton {
            text: "Calibrate Scale";
            enabled: AppState.local-scale-configured || AppState.remote-scale-configured;
            clicked => {
                root.state = AppSettingsState.ScaleCalibration;
            }
        }

        SettingsButton {
            text: "Remote Scale(s) Information";
            clicked => {
                root.state = AppSettingsState.ScalesInformation;
            }
        }
    }

    if state == AppSettingsState.ScaleCalibration: ScaleCalibration {
        cancel-clicked => {
            root.state = AppSettingsState.Buttons;
        }
        ok-clicked => {
            root.state = AppSettingsState.Buttons;
            root.done();
        }
    }

    if state == AppSettingsState.ScalesInformation: ScalesInformation {
        clicked => {
            root.state = AppSettingsState.Buttons;
        }
    }
}
