import {
    ListView,
    GridBox,
    VerticalBox,
    HorizontalBox,
    Button,
    ComboBox,
    SpinBox,
    ScrollView,
} from "std-widgets.slint";

import {
    FrameworkBackend,
    FrameworkState,
    OtaState,
    WebConfigState,
} from "framework/framework.slint";
import { Terminal } from "framework/terminal.slint";
import { Settings } from "framework/settings.slint";
import { Title, MyText, MyButton } from "framework/widgets.slint";

import { Utils } from "utils.slint";
import {
    AppBackend,
    AppState,
    AppConsts,
    ControlState,
    StatusType,
} from "app.slint";
import { ControlPanel } from "controlpanel.slint";
import { SelectPrinter } from "select-printer.slint";
import { AppSettings } from "app-settings.slint";
import { NumPad } from "numpad.slint";
// import { FilamentInfo } from "filament-info.slint";
// import { FilamentInfoMode } from "app.slint";
import { NewTagScan } from "new-tag-scan.slint";
import { StagingOperations } from "staging-operations.slint";
import { TrayOperations } from "tray-operations.slint";
import { MessageBox } from "message-box.slint";
import { AppOtaSelect } from "ota.slint";
import { Storage } from "storage.slint";
import { Slots } from "slots.slint";

// reexport to rust

export { FrameworkState, FrameworkBackend }
export { AppState, AppBackend } 

export component AppWindow inherits Window {
    width: FrameworkState.display-width;
    height: FrameworkState.display-height;
    default-font-family: "Arial";

    function full-screen-dialog-open() -> bool {
      return AppState.control-state == ControlState.NewTagScan || AppState.control-state == ControlState.StagingSelected || AppState.control-state == ControlState.TraySelected;
    }

    property <int> current-page: (FrameworkState.web-config-state == WebConfigState.Started-AP || FrameworkState.web-config-state == WebConfigState.Started-STA-Displayed) ? 2 : (AppState.control-state == ControlState.Booting || /*AppState.control-state == ControlState.ConnectingToPrinter ||*/ AppState.control-state == ControlState.BootFailed) ? 0 : 1;
    changed current-page => {
        if current-page != 0 && terminal.is-scrolled() { // if maybe moved away from terminal 
          reset-terminal-scroll.running = true;
        }
        if current-page == 0 {
            reset-terminal-scroll.running = false;
        }
        if FrameworkState.web-config-state == WebConfigState.Starting || FrameworkState.web-config-state == WebConfigState.Started-STA || FrameworkState.web-config-state == WebConfigState.Started-AP {
            if current-page != 2 {
                AppBackend.read-tag-mode();
            } else {
                AppBackend.web-config-web-app();
            }
        }
    }
    property <int> current-page-x: 0;

    reset-terminal-scroll := Timer {
        interval: 60s;
        triggered => {
        // for some reason calling a function in terminal panics slint, so I need to set internal properties instead
        terminal.scroll-offset-from-end = 0;
            terminal.locked-offset = 0;
            self.running = false;
        }
    }

    sgr := SwipeGestureHandler {
        width: parent.width;
        height: parent.height;
        property <length> topx: -FrameworkState.display-width;
        handle-swipe-up: current-page < 2 && (!AppState.select-printer) && !full-screen-dialog-open();
        handle-swipe-down: current-page > 0 && (!AppState.select-printer) && !full-screen-dialog-open();
        handle-swipe-left: (current_page_x == 0 || topx == 0px) && !full-screen-dialog-open();
        handle-swipe-right: (current-page_x == 1 || topx == -FrameworkState.display-width) && !full-screen-dialog-open();
        swiped => {
            if FrameworkState.ota-state != OtaState.Started {
                if self.handle-swipe-down && self.current-position.y > self.pressed-position.y + FrameworkState.swipe-y-length {
                    // swipe down 
                    current-page -= 1;
                } else if self.handle-swipe-up && self.current-position.y < self.pressed-position.y - FrameworkState.swipe-y-length {
                    // swipe up
                    current-page += 1;
                } else if current-page == 1 {
                   // right left swipe available only when current-page is 1
                    if self.handle-swipe-left && self.current-position.x < self.pressed-position.x - FrameworkState.swipe-x-length {
                      // swipe left
                      // if order is important
                      if topx == 0px {
                          // on left top pane showing storage
                          topx = -FrameworkState.display-width;
                      } else if current-page_x == 0 {
                         // on main screen
                         AppState.select-printer = true;
                         current-page_x = 1;
                         current-page = current-page; // this looks strange, but to 'cut' the automatic state based vertical positioning tht scrolls on events which is confusing after manual touch
                      }
                    } else if self.handle-swipe-right && self.current-position.x > self.pressed-position.x - FrameworkState.swipe-x-length {
                      // swipe right
                      // if order is important
                      if current-page_x == 1 {
                        // if on select priner page
                        AppState.select-printer = false;
                        current-page_x = 0;
                       } else if topx == -FrameworkState.display-width {
                        // on main display
                        topx = 0px;
                      }
                    }
                }
            }
        }

        left-pages := VerticalLayout {
            x: - current-page_x * FrameworkState.display-width;
            y: - current-page * FrameworkState.display-height;
            animate y {
                duration: 1000ms;
                easing: ease-in-out;
            }
            animate x {
                duration: 1000ms;
                easing: ease-in-out;
            }

            // Page 0 - Terminal
            terminal := Terminal {
                text: FrameworkState.term-text;
                height: root.height;
                width: root.width;
                background: #16161e;
            }

            // Page 1 :  App Window - ControlPanel at the bottom and Storage <-> Slots at the top (swipable left/right)
            if !full-screen-dialog-open(): page1 := Rectangle {
                background: white;
                height: parent.height;
                width: parent.width;
                VerticalLayout {
                    height: parent.height;
                    width: parent.width;
                    alignment: stretch;
                    top := HorizontalLayout {
                        x: topx;
                        animate x {
                            duration: 1000ms;
                            easing: ease-in-out;
                        }
                        Storage {
                            width: FrameworkState.display-width;
                        }

                        Rectangle {
                            VerticalLayout { // for some reason VerticalLayout adds the required spacing below
                                slots := Slots {
                                    visible: !AppState.no-printers-configured;
                                    width: FrameworkState.display-width;
                                }
                            }

                            if AppState.no-printers-configured: VerticalLayout {
                                Rectangle {
                                    width: FrameworkState.display-width;
                                    border-width: 1px;
                                    border-color: black;
                                    MyText {
                                        text: "No Printer Configured - Inventory Mode";
                                    }
                                }
                            }
                        }
                    }

                    bottom := ControlPanel {
                        showing: current-page == 1 && current-page-x == 0;
                        clicked-ota => {
                            root.current-page = 2;
                            FrameworkState.ota-clear-message();
                            FrameworkState.ota-state = OtaState.Checking;
                            AppBackend.ota-check-firmwares();
                        }
                        staging-section-width: (root.width - 4*AppConsts.trays-spacing)/5; //slots.slot-width;
                        button-width: self.staging-section-width;
                    }
                }
            }

            if !full-screen-dialog-open(): page3 := AppSettings {
                width: root.width;
                height: root.height;
                done => { // not used, but if we want to in the future
                    root.current-page = 1;
                }
                // TODO: Can move Checking also to Framework Ota 
                if FrameworkState.ota-state == OtaState.UserInput: AppOtaSelect {
                    width: root.width;
                    height: root.height;
                }
            }
        }

        if !full-screen-dialog-open(): SelectPrinter {
            selected => {
                AppState.select-printer = false;
                current-page-x = 0;
            }
            x: left-pages.x + FrameworkState.display-width;
        }
    }

    if AppState.control-state == ControlState.NewTagScan: new-tag-scan := NewTagScan {
        width: root.width;
        height: root.height;
    }

    if AppState.control-state == ControlState.StagingSelected: staging-selected := StagingOperations {
        width: root.width;
        height: root.height;
    }

    if AppState.control-state == ControlState.TraySelected: tray-selected := TrayOperations {
        width: root.width;
        height: root.height;
    }

    if AppState.message-box-text != "": MessageBox {
        width: root.width;
        height: root.height;
        dialog-width: 416px;
        dialog-height: 262px - (self.dialog-text2 == "" ? 76px : 0px);
        dialog-title: AppState.message-box-title;
        dialog-text: AppState.message-box-text;
        dialog-text2: AppState.message-box-text2;
        dialog-background: AppState.message-box-type == StatusType.Success ? green.brighter(1.0) : AppState.message-box-type == StatusType.Error ? red : skyblue;
        dialog-button-text: "Ok" + (AppState.message-box-timeout != 0 ? " (\{AppState.message-box-timeout})" : "");
        clicked => {
            AppState.hide-message-box();
        }

        Timer {
            interval: 1s;
            running: AppState.message-box-text != "" && AppState.message-box-timeout != 0;
            triggered => {
                AppState.message-box-timeout = AppState.message-box-timeout - 1;
                if AppState.message-box-timeout == 0 {
                    AppState.hide-message-box();
                }
            }
        }
    }
}
