import { FrameworkState } from "framework/framework.slint";
import { MyText, Title } from "framework/widgets.slint";
import { Utils } from "utils.slint";
import { AppBackend, AppConsts, AppState, ControlState, UiGenericSlot } from "app.slint";

component GenericSlot inherits Rectangle {
    in property <UiGenericSlot> slot;

    height: 52px;
    background: slot.colors.length > 0 ? #00000000 : white;
    border-width: area.pressed || AppState.control-state == ControlState.TraySelect || slot.used_in_print ? 3px : 1px;
    border-color: slot.used_in_print ? #001dff : black;

    if slot.colors.length > 0 && slot.colors_have_alpha: Image {
        image-fit: preserve;
        horizontal-alignment: left;
        vertical-alignment: top;
        width: parent.width;
        height: parent.height;
        source: AppState.color-checkerboard-bg;
    }

    if slot.colors.length > 0: HorizontalLayout {
        width: parent.width;
        height: parent.height;
        spacing: 0px;
        for stripe-color in slot.colors: Rectangle {
            horizontal-stretch: 1;
            background: stripe-color;
        }
    }

    HorizontalLayout {
        padding-left: 8px;
        padding-right: 8px;
        spacing: 8px;

        Rectangle {
            width: 68px;
            MyText {
                text: slot.name;
                horizontal-alignment: left;
                vertical-alignment: center;
                color: slot.colors.length > 0 ? Utils.contrasting_color(slot.colors[0]) : black;
            }
        }

        Rectangle {
            MyText {
                text: slot.material == "" ? slot.state : slot.material;
                horizontal-alignment: left;
                vertical-alignment: center;
                color: slot.colors.length > 0 ? Utils.contrasting_color(slot.colors[0]) : black;
            }
        }

        Rectangle {
            width: 74px;
            MyText {
                text: slot.spool_id;
                horizontal-alignment: right;
                vertical-alignment: center;
                color: slot.colors.length > 0 ? Utils.contrasting_color(slot.colors[0]) : black;
            }
        }
    }

    area := TouchArea {
        width: parent.width;
        height: parent.height;
        clicked => {
            if AppState.control-state == ControlState.TraySelect {
                AppBackend.set-staging-to-generic-slot(slot.id);
            }
        }
    }
}

export component GenericSlots inherits Rectangle {
    width: FrameworkState.display-width;
    background: white;

    VerticalLayout {
        spacing: AppConsts.trays-spacing;
        for group in AppState.generic-slot-groups: VerticalLayout {
            spacing: 2px;
            Title {
                text: group.name + " (" + group.kind + ")";
                text-color: white;
                background: AppConsts.title-gradient;
            }
            for slot in group.slots: GenericSlot {
                slot: slot;
            }
        }
    }
}
