import { Title } from "../ui/select-printer.slint";
import { MyButton, MyText } from "./framework/widgets.slint";
import { Utils } from "utils.slint";
import { AppState } from "app.slint";

export component MessageBox inherits Rectangle {
    callback clicked;
    in property <color> dialog-background: skyblue;
    in property <color> dialog-title-background: beige;
    in property <length> dialog-width: 416px;
    in property <length> dialog-height: 242px;
    in property <string> dialog-title: "Message";
    in property <string> dialog-text;
    in property <string> dialog-text2;
    in property <string> dialog-button-text: "Ok";
    in property <bool> dialog-dismissible: true;
    back-rect := Rectangle {
        x: (root.width - root.dialog-width) / 2;
        y: (root.height - root.dialog-height) / 2;
        border-radius: 10px;
        border-color: black;
        border-width: 1px;
        background: dialog-background;
        width: dialog-width;
        height: dialog-height;
        VerticalLayout {
            padding-bottom: 10px;
            Title {
                border-top-right-radius: 10px;
                border-top-left-radius: 10px;
                text: dialog-title;
                background: dialog-title-background;
            }

            Rectangle {
                VerticalLayout {
                    padding-top: 10px;
                    Rectangle {
                        HorizontalLayout {
                            padding-left: 5px;
                            padding-right: 5px;
                            width: dialog-width;
                            alignment: center;
                            MyText {
                                horizontal-alignment: left;
                                text: dialog-text;
                                wrap: word-wrap;
                                color: Utils.contrasting_color(root.dialog-background);
                            }
                        }
                    }

                    Rectangle {
                        HorizontalLayout {
                            padding-left: 5px;
                            padding-right: 5px;
                            width: dialog-width;
                            alignment: center;
                            MyText {
                                horizontal-alignment: left;
                                text: dialog-text2;
                                wrap: word-wrap;
                                color: Utils.contrasting_color(root.dialog-background);
                            }
                        }
                    }
                }
            }

            HorizontalLayout {
                alignment: center;
                MyButton {
                    width: 120px;
                    height: 56px;
                    enabled: root.dialog-dismissible;
                    text: root.dialog-button-text;
                    clicked => {
                        root.clicked();
                    }
                    // Next two rectangles are to get a round border on the button
                    Rectangle {
                        width: 128px;
                        height: 64px;
                        background: #0000;
                        border-radius: 10px;
                        border-color: back-rect.background;
                        border-width: 5px;
                    }

                    Rectangle {
                        width: 120px;
                        height: 56px;
                        background: #0000;
                        border-radius: 10px;
                        border-color: black;
                        border-width: 1px;
                    }
                }
            }
        }
    }
}
