import {
    MyText,
    MyButton,
    ButtonType,
    WizardButtons,
    Title,
} from "framework/widgets.slint";
import { NumPad } from "numpad.slint";
import {
    AppBackend,
    AppState,
    ControlState,
    NewTagScanPage,
    NewTagOperation,
    SpoolScaleState,
    UiSpoolRecordDisplay,
    NewScannedTagType,
} from "app.slint";
import { Utils } from "utils.slint";
import { ScaleWeightDisplay } from "app-widgets.slint";
import { SpoolDisplay, SpoolDisplayMode } from "spool-display.slint";
import { UpdateWeightPage } from "common-operations.slint";

enum AddSelection {
  None,
  Yes,
  No
}

component SpoolDefinitionTagScannedPage inherits Rectangle {
    background: white;
    property <AddSelection> add-selection: None;

    function pressed(operation: AddSelection) {
        add-selection = (operation == AddSelection.Yes) ? AddSelection.Yes : AddSelection.No;
    }

    VerticalLayout {
        Title {
            text: "New \{AppState.new-tag-scan-definition-type} Tag Scanned";
        }

        VerticalLayout {
            alignment: start;
            padding: 5px;
            padding-top: 10px;
            spacing: 8px;

            MyText {
                wrap: word-wrap;
                text: "The scanned tag is \{AppState.new-tag-scan-definition-type} tag, and isn't linked to your inventory.";
                color: black;
            }

            MyText {
                text: "Import tag data to the inventory as a new spool?";
            }

            add-rec-yes := MyButton {
                type: ButtonType.RadioButton;
                pushed: add-selection == AddSelection.Yes;
                height: 56px;
                text: "Yes, Import Data as New Spool Record";
                pressed => {
                    pressed(AddSelection.Yes);
                }
            }

            add-red-no := MyButton {
                type: ButtonType.RadioButton;
                pushed: add-selection == AddSelection.No;
                height: 56px;
                text: "No, Ignore the Data";
                pressed => {
                    pressed(AddSelection.No);
                }
            }
        }

        WizardButtons {
            next-enabled: add-selection != AddSelection.None;
            next-clicked => {
                if add-selection == AddSelection.Yes {
                   // Switch to SpoolDisplay to show the scanned spool information
                   if AppState.new-tag-scan-definition-type == "Bambu Lab" {
                        AppState.new-tag-scan-page = NewTagScanPage.BambulabSpoolTypeSelection;
                    } else {
                        AppState.new-tag-scan-page = NewTagScanPage.SpoolDisplay;
                    }
                } else if add-selection == AddSelection.No {
                    AppState.new-tag-scan-tag-type = NewScannedTagType.SimpleTag;
                    // DON'T set the AppState.new-tag-scan-tag-definition-type, this is used for filling in the type of tag even if data in't imported
                    AppState.new-tag-scan-page = NewTagScanPage.OperationSelect;
                }
            }

            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
        }
    }
}

enum BambulabSpoolTypeSelection {
  None,
  LowTemp,
  HighTemp,
  Other,
}
component BambulabSpoolTypePage inherits Rectangle {
    width: 480px;
    height: 320px;
    background: white;
    property <BambulabSpoolTypeSelection> spool-selection: None;

    function pressed(operation: BambulabSpoolTypeSelection) {
        spool-selection = operation;
    }

    VerticalLayout {
        Title {
            text: "New \{AppState.new-tag-scan-definition-type} Tag Scanned";
        }

        VerticalLayout {
            alignment: start;
            padding: 5px;
            padding-top: 10px;
            spacing: 8px;

            MyText {
                width: parent.width;
                wrap: word-wrap;
                text: "Available filament est. needs empty-spool weight.";
                color: black;
            }

            MyText {
                text: "What spool type is used with this tag?";
            }

            lowtemp := MyButton {
                type: ButtonType.RadioButton;
                pushed: spool-selection == BambulabSpoolTypeSelection.LowTemp;
                height: 45px;
                text: "Low Temp (≤ 70°C) / Light Gray (~250g)"; // 208-212 + 38 (if change, change also below)
                pressed => {
                    pressed(BambulabSpoolTypeSelection.LowTemp);
                }
            }

            hightemp := MyButton {
                type: ButtonType.RadioButton;
                pushed: spool-selection == BambulabSpoolTypeSelection.HighTemp;
                height: 45px;
                text: "High Temp (≤ 90°C) / Dark Gray (~260g)"; // 223 + 38, (if change, change also below)
                pressed => {
                    pressed(BambulabSpoolTypeSelection.HighTemp);
                }
            }

            other := MyButton {
                type: ButtonType.RadioButton;
                pushed: spool-selection == BambulabSpoolTypeSelection.Other;
                height: 45px;
                text: "Other (Can be entered manually later)";
                pressed => {
                    pressed(BambulabSpoolTypeSelection.Other);
                }
            }
        }

        WizardButtons {
            next-enabled: spool-selection != BambulabSpoolTypeSelection.None;
            next-clicked => {
                AppState.new-tag-scan-empty-spool-weight = spool-selection == BambulabSpoolTypeSelection.LowTemp ? 250 : spool-selection == BambulabSpoolTypeSelection.HighTemp ? 260 : 0;
                AppState.new-tag-scan-page = NewTagScanPage.SpoolDisplay;
            }
            back-clicked => {
                AppState.new-tag-scan-page = NewTagScanPage.SpoolDefinitionTagScanned;
            }
            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
        }
    }
}

component OperationSelectionStep inherits Rectangle {
    width: 480px;
    height: 320px;
    background: white;

    pure function staged-spool-id() -> string {
        return AppState.spool-staging-info.spool-record.id;
    }

    pure function staged-spool-tagged() -> bool {
        let staged-id = staged-spool-id();
        return staged-id != "" && AppBackend.spool-tag-count(staged-id) > 0;
    }

    function pressed(operation: NewTagOperation) {
        AppState.new-tag-operation = AppState.new-tag-operation == operation ? NewTagOperation.None : operation;
    }

    VerticalLayout {
        Title {
            text: AppState.new-tag-scan-tag-type == NewScannedTagType.SimpleTag ? "New Tag Scanned" : "New \{AppState.new-tag-scan-definition-type} Tag Scanned";
        }

        VerticalLayout {
            alignment: start;
            padding-top: 4px;
            spacing: 4px;
            if AppState.new-tag-scan-tag-type == NewScannedTagType.DefinitionTag: Rectangle {
                MyText {
                    width: parent.width;
                    wrap: word-wrap;
                    text: "\{AppState.new-tag-scan-definition-type} tag data imported as spool ID: \{AppState.new-tag-scan-spool-id}.";
                    color: black;
                }
            }

            VerticalLayout {
                spacing: 4px;
                if AppState.new-tag-scan-tag-type == NewScannedTagType.SimpleTag: b1 := MyButton {
                    type: ButtonType.RadioButton;
                    pushed: AppState.new-tag-operation == NewTagOperation.LinkTagToSpoolId;
                    height: 51px;
                    text: "Link Tag to an Untagged Spool";
                    pressed => {
                        pressed(NewTagOperation.LinkTagToSpoolId);
                    }
                }

                if AppState.new-tag-scan-tag-type == NewScannedTagType.SimpleTag: b1b := MyButton {
                    type: ButtonType.RadioButton;
                    pushed: AppState.new-tag-operation == NewTagOperation.LinkAnotherTagToTaggedSpool;
                    height: 51px;
                    text: "Link Another Tag to a Tagged Spool";
                    pressed => {
                        pressed(NewTagOperation.LinkAnotherTagToTaggedSpool);
                    }
                }

                if AppState.new-tag-scan-tag-type == NewScannedTagType.SimpleTag && staged-spool-id() != "": b1c := MyButton {
                    type: ButtonType.RadioButton;
                    pushed: AppState.new-tag-operation == NewTagOperation.LinkTagToStagedSpool;
                    height: 51px;
                    text: staged-spool-tagged() ? "Link Another Tag to Staged Spool (\{staged-spool-id()})" : "Link Tag to Staged Spool (\{staged-spool-id()})";
                    pressed => {
                        pressed(NewTagOperation.LinkTagToStagedSpool);
                    }
                }

                // this should be displayed both for simple tag and definition tag
                if AppBackend.recently_added_spool_id_if_untagged() != "": MyButton {
                    pushed: AppState.new-tag-operation == NewTagOperation.LinkTagToRecentlyAddedSpool;
                    type: ButtonType.RadioButton;
                    height: 51px;
                    text: (AppState.new-tag-scan-tag-type == NewScannedTagType.SimpleTag) ? "Link tag to recently added spool ID: \{AppBackend.recently_added_spool_id_if_untagged()}" : "Link tag to the imported spool ID: \{AppBackend.recently_added_spool_id_if_untagged()}";
                    pressed => {
                        pressed(NewTagOperation.LinkTagToRecentlyAddedSpool);
                    }
                }

                 if AppState.new-tag-scan-tag-type == NewScannedTagType.DefinitionTag && AppState.new-tag-scan-definition-type == "Bambu Lab": 
                VerticalLayout {
                    padding-top: 12px;
                    MyText {
                        width: parent.width;
                        wrap: word-wrap;
                        text: "IMPORTANT : Bambu Lab spools have a tag on each side. To link both, right after linking this tag, scan the other side and link (DON'T IMPORT, ONLY LINK) it to the newly staged spool (or later by selecting its ID).";
                        color: black;
                    }
                }
            }
        }

        WizardButtons {
            next-enabled: AppState.new-tag-operation != NewTagOperation.None;
            next-clicked => {
                // AppState.new-tag-operation = selected-operation;
              if AppState.new-tag-operation == NewTagOperation.LinkTagToStagedSpool {
                    AppState.new-tag-scan-spool-id = staged-spool-id();
                    AppState.new-tag-scan-page = NewTagScanPage.SpoolDisplay;
                } else if AppState.new-tag-operation == NewTagOperation.LinkTagToSpoolId || AppState.new-tag-operation == NewTagOperation.LinkAnotherTagToTaggedSpool {
                    AppState.new-tag-scan-page = NewTagScanPage.SpoolSelect;
                } else {
                    AppState.new-tag-scan-spool-id = AppBackend.recently_added_spool_id_if_untagged();
                    if AppState.new-tag-scan-tag-type == NewScannedTagType.SimpleTag {
                        AppState.new-tag-scan-page = NewTagScanPage.SpoolDisplay;
                    } else { // DefinitionTag
                      // skip display since we saw it already
                        AppBackend.link-tag-to-untagged-spool-id(AppState.new-tag-scan-tag-id, AppState.new-tag-scan-definition-type, AppState.new-tag-scan-spool-id, !AppState.is-scale-usable-now());
                    }
                }
            }
            cancel-text: (AppState.new-tag-scan-tag-type == NewScannedTagType.SimpleTag) ? "× Cancel" : "Done";
            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
        }
    }
}

component SpoolSelectStep inherits Rectangle {
    background: white;
    in-out property <int> spool-id: num-pad.number;
    VerticalLayout {
        Title {
            text: AppState.new-tag-operation == NewTagOperation.LinkAnotherTagToTaggedSpool ? "Enter Tagged Spool Id" : "Enter Untagged Spool Id";
        }

        Rectangle {
            num-pad := NumPad {
                number: AppState.new-tag-scan-spool-id-int;
                ok-visible: false;
                display-postfix: "";
            }
        }

        wiz-buttons := WizardButtons {
            back-enabled: true;
            next-enabled: true;
            back-clicked => {
                AppState.new-tag-scan-page = NewTagScanPage.OperationSelect;
            }
            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
            next-clicked => {
                num-pad.display-error = AppState.new-tag-operation == NewTagOperation.LinkAnotherTagToTaggedSpool ? AppBackend.can-link-tagged-spool-to-tag(num-pad.number) : AppBackend.can-link-untagged-spool-to-tag(num-pad.number);
                if num-pad.display-error == "" {
                    AppState.new-tag-scan-spool-id = num-pad.number;
                    AppState.new-tag-scan-spool-id-int = num-pad.number;
                    AppState.new-tag-scan-page = NewTagScanPage.SpoolDisplay;
                }
            }
        }
    }
}

component V1TagPromptStep inherits Rectangle {
    width: 480px;
    height: 320px;
    property <NewTagOperation> selected-operation: None;
    property <bool> last-step: !AppState.is-scale-usable-now();
    function pressed(operation: NewTagOperation) {
        selected-operation = selected-operation == operation ? NewTagOperation.None : operation;
    }
    background: white;
    VerticalLayout {
        Title {
            text: "Early Version Tag That's Not in Inventory";
        }

        VerticalLayout {
            alignment: start;
            padding: 5px;
            spacing: 5px;
            MyText {
                text: "This scanned tag is from an earlier SpoolEase version and isn’t in your inventory.";
                wrap: word-wrap;
            }

            MyText {
                text: "Please choose an action:";
            }

            b1 := MyButton {
                type: ButtonType.RadioButton;
                pushed: selected-operation == NewTagOperation.AddV1TagToInventory;
                height: 56px;
                text: "Add Spool Data to Inventory";
                pressed => {
                    pressed(NewTagOperation.AddV1TagToInventory);
                }
            }

            b2 := MyButton {
                pushed: selected-operation == NewTagOperation.EraseV1Tag;
                type: ButtonType.RadioButton;
                height: 56px;
                text: "Erase Tag to Use it Without the Data";
                pressed => {
                    pressed(NewTagOperation.EraseV1Tag);
                }
            }
        }

        WizardButtons {
            back-enabled: false;
            next-enabled: selected-operation != NewTagOperation.None;
            cancel-enabled: true;
            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
            next-clicked => {
                if selected-operation == NewTagOperation.AddV1TagToInventory {
                    AppBackend.add-v1-tag-to-inventory(AppState.new-tag-scan-tag-id, AppState.new-tag-scan-definition-info, last-step);
                } else {
                    AppState.erase-tag-by-tag-id-start(AppState.new-tag-scan-tag-id);
                }
            }
        }
    }
}

component SpoolDisplayStep inherits Rectangle {
    in-out property <string> cancel-text: "";
    in-out property <string> next-text: "";
    in property <UiSpoolRecordDisplay> spool-display;
    property <bool> last-step: !AppState.is-scale-usable-now();
    VerticalLayout {
        SpoolDisplay {
            show-title: true;
            spool-display: root.spool-display;
            title: AppState.new-tag-scan-tag-type == NewScannedTagType.DefinitionTag ? "Spool Tag Information" : "";
            mode: AppState.new-tag-scan-tag-type == NewScannedTagType.DefinitionTag ? SpoolDisplayMode.ImportTagDefinition : SpoolDisplayMode.Normal;
        }

        WizardButtons {
            back-enabled: true;
            next-enabled: true;
            cancel-enabled: true;
            cancel-text: root.cancel-text;
            next-text: AppState.new-tag-scan-tag-type == NewScannedTagType.SimpleTag ? "✓ Link Tag" + (root.last-step ? "" : " ▶") : "✓ Import ▶";
            back-clicked => {
                if AppState.new-tag-scan-tag-type == NewScannedTagType.SimpleTag {
                    AppState.new-tag-scan-page = NewTagScanPage.SpoolSelect;
                } else if AppState.new-tag-scan-tag-type == NewScannedTagType.DefinitionTag {
                    if AppState.new-tag-scan-definition-type == "Bambu Lab" {
                        AppState.new-tag-scan-page = NewTagScanPage.BambulabSpoolTypeSelection;
                    } else {
                        AppState.new-tag-scan-page = NewTagScanPage.SpoolDefinitionTagScanned;
                    }
                }
            }
            next-clicked => {
                self.back-enabled = false;
                self.next-enabled = false;
                cancel-text = "Close";
                // perform action
                if AppState.new-tag-scan-tag-type == NewScannedTagType.SimpleTag {
                    if AppState.new-tag-operation == NewTagOperation.LinkTagToStagedSpool {
                        if AppBackend.spool-tag-count(AppState.new-tag-scan-spool-id) > 0 {
                            AppBackend.link-tag-to-tagged-spool-id(
                                AppState.new-tag-scan-tag-id,
                                AppState.new-tag-scan-definition-type,
                                AppState.new-tag-scan-spool-id,
                                last-step,
                            );
                        } else {
                            AppBackend.link-tag-to-untagged-spool-id(AppState.new-tag-scan-tag-id, AppState.new-tag-scan-definition-type, AppState.new-tag-scan-spool-id, last-step);
                        }
                    } else if AppState.new-tag-operation == NewTagOperation.LinkAnotherTagToTaggedSpool {
                        AppBackend.link-tag-to-tagged-spool-id(
                            AppState.new-tag-scan-tag-id,
                            AppState.new-tag-scan-definition-type,
                            AppState.new-tag-scan-spool-id,
                            last-step,
                        );
                    } else {
                        AppBackend.link-tag-to-untagged-spool-id(AppState.new-tag-scan-tag-id, AppState.new-tag-scan-definition-type, AppState.new-tag-scan-spool-id, last-step);
                    }
                } else {
                  // TODO: Add call to AppBackend to add spool record, which will 
                  // (1) import the tag to the inventory & set it as recently added spool
                  // (2) once completed will trigger move here to next step
                  AppBackend.import-definition-tag-to-inventory(AppState.new-tag-scan-definition-type, AppState.new-tag-scan-definition-info, AppState.new-tag-scan-empty-spool-weight);
                }
            }
            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
        }
    }
}

component ImportDefinitionNoticePage inherits Rectangle {
    width: 480px;
    height: 320px;
    VerticalLayout {

        Title {
            text: "\{AppState.new-tag-scan-definition-type} Tag Information Imported";
        }

        Rectangle {
            background: white;

            VerticalLayout {
                alignment: space-around;
                padding: 20px;
                spacing: 5px;
                MyText {
                    horizontal-alignment: center;
                    text: "Tag Information Imported to Spool \{AppState.new-tag-scan-spool-id}";
                }

                MyText {
                    text: "Imported data may still be incomplete or inaccurate, and some features might not work as expected.";
                    wrap: word-wrap;
                }

                MyText {
                    text: "Please review the spool record in the inventory app and complete or correct the missing details.";
                    wrap: word-wrap;
                }
            }
        }

        WizardButtons {
            back-enabled: false;
            next-enabled: true;
            next-text: "Continue";
            cancel-enabled: false;
            next-clicked => {
                AppState.new-tag-scan-page = NewTagScanPage.OperationSelect;
            }
            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
        }
    }
}

component StatusDisplayPage inherits Rectangle {
    in-out property <bool> success: AppState.new-tag-scan-status == "";
    in-out property <string> message: self.success ? "Tag Linked to Spool Successfuly" : AppState.new-tag-scan-status;
    VerticalLayout {
        Rectangle {
            background: success ? lightgreen : red;
            MyText {
                text: message;
                color: Utils.contrasting_color(parent.background);
            }
        }

        WizardButtons {
            back-enabled: false;
            next-enabled: false;
            cancel-enabled: true;
            cancel-text: "Close";
            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
        }
    }
}

export component NewTagScan inherits Rectangle {
    width: 480px;
    height: 320px;
    property <UiSpoolRecordDisplay> spool-display: AppState.new-tag-scan-tag-type == NewScannedTagType.SimpleTag || AppState.new-tag-scan-spool-id != "" ? AppBackend.get-spool-record-display(AppState.new-tag-scan-spool-id) : AppBackend.get-spool-tag-definition-display(AppState.new-tag-scan-definition-type, AppState.new-tag-scan-definition-info, AppState.new-tag-scan-empty-spool-weight);

    if AppState.new-tag-scan-page == NewTagScanPage.OperationSelect: oper-select := OperationSelectionStep { }

    if AppState.new-tag-scan-page == NewTagScanPage.SpoolSelect: spool-select := SpoolSelectStep { }

    if AppState.new-tag-scan-page == NewTagScanPage.SpoolDisplay: spool-display := SpoolDisplayStep {
        spool-display: root.spool-display;
    }

    if AppState.new-tag-scan-page == NewTagScanPage.UpdateWeight: update-weight-display := UpdateWeightPage {
        final-step: true;
        title: "Linking Tag Succeeded, Measure Weight";
        user-prompt: "Now is a good time to measure spool weight,\nPlease place it on the scale.";
        weight-current: spool-display.spool-record.weight-current;
        weight-new: spool-display.spool-record.weight-new;
        spool-id: spool-display.spool-record.id;
        cancel-clicked => {
            AppState.control-state = ControlState.PostAction; // so will show the message that tag was scanned from previous step
        }
        back-clicked => {
            AppState.staging-operation-page = AppState.prev-staging-operation-page;
        }
    }

    if AppState.new-tag-scan-page == NewTagScanPage.StatusDisplay: status-display := StatusDisplayPage { }

    if AppState.new-tag-scan-page == NewTagScanPage.V1TagPrompt: v1-prompt := V1TagPromptStep { }

    if AppState.new-tag-scan-page == NewTagScanPage.SpoolDefinitionTagScanned: spool-definition-tag-scanned := SpoolDefinitionTagScannedPage { }

    if AppState.new-tag-scan-page == NewTagScanPage.BambulabSpoolTypeSelection: bambulab-spool-type-selection := BambulabSpoolTypePage { }

    if AppState.new-tag-scan-page == NewTagScanPage.ImportDefinitionNotice: import-definition-notice := ImportDefinitionNoticePage { }
}
