import { MyButton, MyText } from "framework/widgets.slint";


export component Display inherits Rectangle {
    in-out property <int> number;
    border-color: black;
    border-width: 1px;
    in-out property <string> postfix: " g";
    in-out property <string> display-error: "";

    HorizontalLayout {
        padding-right: 20px;
        padding-left: 10px;
        Rectangle {
            MyText {
                text: display-error;
                color: red;
            }
        }

        VerticalLayout {
            horizontal-stretch: 1;
            padding: 4px;
            alignment: center;
            Text {
                // preferred-height: 1px;
                min-height: 0px;
                text: "\{number}\{postfix}";
                font-size: 32px;
                horizontal-alignment: right;
                color: black;
            }
        }
    }
}

export component NumButton inherits MyButton {
    in property <int> digit;
    text: "\{digit}";
    callback key-pressed(digit: int);
    preferred-width: 1px; // so all equal
    preferred-height: 1px;
    clicked => {
        key-pressed(digit);
    }
}

////////////////////////

export component NumPad inherits Rectangle {
    in property <int> max-digits: 4;
    in property <int> min-value: 0;
    in property <int> max-value: 0;
    in property <bool> ok-visible: true;
    width: 288px;
    callback ok-clicked;
    callback value-changed(value: int, done: bool);
    in property <string> title;
    background: white;
    in-out property <int> number;
    in-out property <string> display-postfix: " g";
    in-out property <string> display-error;
    pure function bounded() -> bool {
        return max-value > 0;
    }
    pure function single-digit-bound() -> bool {
        return bounded() && max-value < 10;
    }
    pure function digit-disabled(digit: int) -> bool {
        if !bounded() {
            return false;
        }
        if single-digit-bound() {
            return digit == 0 || digit > max-value || digit < min-value;
        }
        if number == 0 && digit == 0 {
            return true;
        }
        if log(number, 10) >= max-digits - 1 {
            return true;
        }
        let new-value = number * 10 + digit;
        return new-value > max-value;
    }
    pure function ok-enabled() -> bool {
        return ok-visible && (!bounded() || (number >= min-value && number <= max-value));
    }
    function pressed-digit(digit: int) {
        if digit-disabled(digit) {
            return;
        }
        if single-digit-bound() {
            number = digit;
            display-error = "";
            value-changed(number, true);
        } else if log(number, 10) < max-digits - 1 {
            number = number * 10 + digit;
            display-error = "";
            value-changed(number, false);
        }
    }
    main := VerticalLayout {
        Display {
            height: root.height / 5;
            postfix: display-postfix;
            number: root.number;
            display-error: display-error;
        }

        HorizontalLayout {
            vertical-stretch: 1;
            NumButton {
                digit: 7;
                enabled: !root.digit-disabled(self.digit);
                key-pressed(digit) => {
                    pressed-digit(digit);
                }
            }

            NumButton {
                digit: 8;
                enabled: !root.digit-disabled(self.digit);
                key-pressed(digit) => {
                    pressed-digit(digit);
                }
            }

            NumButton {
                digit: 9;
                enabled: !root.digit-disabled(self.digit);
                key-pressed(digit) => {
                    pressed-digit(digit);
                }
            }
        }

        HorizontalLayout {
            NumButton {
                digit: 4;
                enabled: !root.digit-disabled(self.digit);
                key-pressed(digit) => {
                    pressed-digit(digit);
                }
            }

            NumButton {
                digit: 5;
                enabled: !root.digit-disabled(self.digit);
                key-pressed(digit) => {
                    pressed-digit(digit);
                }
            }

            NumButton {
                digit: 6;
                enabled: !root.digit-disabled(self.digit);
                key-pressed(digit) => {
                    pressed-digit(digit);
                }
            }
        }

        HorizontalLayout {
            NumButton {
                digit: 1;
                enabled: !root.digit-disabled(self.digit);
                key-pressed(digit) => {
                    pressed-digit(digit);
                }
            }

            NumButton {
                digit: 2;
                enabled: !root.digit-disabled(self.digit);
                key-pressed(digit) => {
                    pressed-digit(digit);
                }
            }

            NumButton {
                digit: 3;
                enabled: !root.digit-disabled(self.digit);
                key-pressed(digit) => {
                    pressed-digit(digit);
                }
            }
        }

        HorizontalLayout {
            NumButton {
                text: "Del";
                key-pressed(digit) => {
                    root.number = floor(root.number / 10);
                    display-error = "";
                    root.value-changed(root.number, false);
                }
            }

            NumButton {
                digit: 0;
                enabled: !root.digit-disabled(self.digit);
                key-pressed(digit) => {
                    pressed-digit(digit);
                }
            }

            NumButton {
                text: ok-visible ? "Ok" : "";
                enabled: !ok-visible || ok-enabled();
                key-pressed(digit) => {
                    if ok-enabled() {
                        root.ok-clicked();
                        root.value-changed(root.number, true);
                    }
                }
            }
        }
    }

    Rectangle {
        y: main.y - 1px;
        width: main.width;
        border-color: black;
        border-width: 1px;
    }
}
