import { MyButton } from "./framework/widgets.slint";
import { AppBackend, AppState, Printer } from "app.slint";
import { Title } from "framework/widgets.slint";
import { Utils } from "utils.slint";

export component Title inherits Rectangle {
    in-out property <string> text;
    height: 40px;
    background: green.brighter(1.0);
    border-color: black;
    border-width: 1px;
    Text {
        vertical-alignment: center;
        horizontal-alignment: center;
        height: 40px;
        text: text;
        font-size: 20px;
        color: Utils.contrasting_color(root.background);
    }
}

export component SelectPrinterButton inherits MyButton {
    in-out property <Printer> printer;
    height: 56px;
    horizontal-alignment: left;
}

export component SelectPrinter inherits VerticalLayout {
  callback selected;
  Title {
      text: "Select Printer";
  }
  for printer[index] in AppState.available_printers: SelectPrinterButton {
      printer: printer;
      height: 60px;
      text: (AppState.curr_printer == index ? "  ✓ ": "      ") + printer.name + (printer.kind == "Bambu" ? "" : " (" + printer.kind + ")") + (AppState.default_printer == index ? " (Default)" : "") + (printer.connected ? ": Connected" : ": Disconnected");
      clicked  => {
        AppBackend.select-printer(index); 
        selected();
      }
  }
}
