import { FrameworkState } from "framework/framework.slint";
import { AppConsts, AppState } from "app.slint";
import { StandardSlotGroups } from "trays.slint";

export component Slots inherits HorizontalLayout {
    out property <length> slot-width: (FrameworkState.display-width - 4 * AppConsts.trays-spacing) / 5;
    width: FrameworkState.display-width;
    spacing: AppConsts.trays-spacing;

    StandardSlotGroups {
        width: parent.width;
    }
}
