import { MyText } from "framework/widgets.slint";
import { LabeledText } from "app-widgets.slint";
import {
    AppBackend,
    AppState,
    UiSlot,
    UiSlotDisplay,
    UiSlotState,
} from "app.slint";

component LabeledInfo inherits LabeledText {
    label-width: 90px;
}

export component SlotDisplay inherits Rectangle {
    background: white;
    in property <UiSlot> slot;
    property <UiSlotDisplay> display: AppBackend.get-slot-display(slot.id);

    VerticalLayout {
        alignment: stretch;
        Rectangle {
            vertical-stretch: 1;
            MyText {
                text: display.filament-title;
            }
        }

        padding: 10px;
        padding-bottom: 5px;

        LabeledInfo {
            vertical-stretch: 1;
            property <UiSlotState> state: slot.state;
            label: "State:";
            text: AppState.ui-slot-state-name(slot.state);
        }

        LabeledInfo {
            vertical-stretch: 1;
            label: "In Slicer:";
            text: display.slicer-name;
        }

        LabeledInfo {
            vertical-stretch: 1;
            horizontal-stretch: 1;
            label: "Color:";
            text: display.color-code;
        }

        HorizontalLayout {
            vertical-stretch: 1;
            alignment: space-between;
            LabeledInfo {
                vertical-stretch: 1;
                label: "PA(K):";
                text: display.pa;
            }

            LabeledInfo {
                label: "Temps: ";
                label-width: 70px;
                text: "\{display.temp-min}°C - \{display.temp-max}°C";
            }
        }

        LabeledInfo {
            vertical-stretch: 1;
            label-width: 240px;
            label: "Consumed Since Loaded:";
            text: display.consumed-since-loaded != 0 ? "\{Math.round(display.consumed-since-loaded * 10) / 10}g" : "–";
        }
    }
}
