import { Title, MyText, MyButton } from "./framework/widgets.slint";
import { AppBackend, AppState, ControlState, UiTray, UiSpoolRecord, UiSpoolRecordDisplay } from "app.slint";
import { Utils } from "utils.slint";
import { FrameworkState, Log } from "framework/framework.slint";
import { LabeledText, TitledText } from "app-widgets.slint";


component LabeledInfo inherits LabeledText {
    label-width: 90px;
}

export component ViewTitle inherits Title {
    horizontal-alignment: center;
    text: "Filament Information";
}

export component ViewButtons inherits HorizontalLayout {
    MyButton {
        horizontal-stretch: 1;
        height: 56px;
        text: "Close";
        clicked => {
            AppState.control-state = ControlState.Ready;
        }
    }
}

component MultiColorTitle inherits Rectangle {
    in property <string> text;
    in property <[color]> colors;
    in property <color> fallback-color: green.brighter(1.0);
    in property <TextHorizontalAlignment> horizontal-alignment: center;
    height: 40px;
    border-color: black;
    border-width: 1px;
    property <int> color-count: colors.length;
    property <length> stripe-width: color-count > 0 ? root.width / color-count : 0px;

    Image {
        width: parent.width;
        height: parent.height;
        source: AppState.title-checkerboard-bg;
    }

    if color-count > 0: HorizontalLayout {
        width: parent.width;
        height: parent.height;
        spacing: 0px;
        for stripe-color[index] in colors: Rectangle {
            horizontal-stretch: 1;
            background: stripe-color;
            clip: true;

            Text {
                x: -index * root.stripe-width;
                width: root.width;
                height: root.height;
                vertical-alignment: center;
                horizontal-alignment: root.horizontal-alignment;
                text: root.text;
                color: Utils.contrasting_color(stripe-color);
                font-size: 20px;
            }
        }
    }

    if color-count == 0: Rectangle {
        width: parent.width;
        height: parent.height;
        background: fallback-color;
        Text {
            width: parent.width;
            height: parent.height;
            vertical-alignment: center;
            horizontal-alignment: root.horizontal-alignment;
            text: root.text;
            color: Utils.contrasting_color(parent.background);
            font-size: 20px;
        }
    }
}

export enum SpoolDisplayMode {
    Normal,
    ImportTagDefinition,
}

component WeightsDisplay inherits Rectangle {
    background: white;
    in-out property <length> vert-spacing: 2px;
    in-out property <string> weight-label;
    in-out property <string> weight-empty;
    in-out property <string> weight-full;
    in-out property <string> weight-net;
    in-out property <string> weight-gross;

    HorizontalLayout {
        spacing: 10px;
        padding: 0px;
        TitledText {
            vert-spacing: vert-spacing;
            label: "Label";
            text: weight-label;
        }

        TitledText {
            vert-spacing: vert-spacing;
            label: "Empty";
            text: weight-empty;
        }

        TitledText {
            vert-spacing: vert-spacing;
            label: "Full";
            text: weight-full;
        }

        TitledText {
            vert-spacing: vert-spacing;
            label: "Net";
            text: weight-net;
        }

        TitledText {
            vert-spacing: vert-spacing;
            label: "Gross";
            text: weight-gross;
        }
    }
}

export component SpoolDisplay inherits Rectangle {
    in-out property <UiSpoolRecordDisplay> spool-display;
    background: white;
    property <color> filament-color: spool-display.color;
    in property <bool> show-title: true;
    in property <string> title: "";
    in property <SpoolDisplayMode> mode: SpoolDisplayMode.Normal;

    VerticalLayout {
        alignment: stretch;
        if show-title: MultiColorTitle {
            vertical-stretch: 0;
            text: title == "" ? "Spool \{spool-display.spool-record.id} Information" : title;
            colors: spool-display.colors;
            fallback-color: spool-display.color;
        }

        VerticalLayout {
            alignment: stretch;
            vertical-stretch: 1;
            padding: 10px;
            padding-bottom: 5px;
            property <string> brand: spool-display.spool-record.brand == "" ? "" : "\{spool-display.spool-record.brand} ";
            property <string> material-subtype: spool-display.spool-record.material-subtype == "" ? "" : " \{spool-display.spool-record.material_subtype}";
            property <string> color-name: spool-display.spool-record.color-name == "" ? "" : " \{spool-display.spool-record.color-name}";
            MyText {
                vertical-stretch: 1;
                horizontal-alignment: center;
                text: "\{brand}\{spool-display.spool-record.material-type}\{material-subtype}\{color-name}";
            }

            LabeledInfo {
                vertical-stretch: mode == SpoolDisplayMode.ImportTagDefinition ? 2 : 1;
                label: "Note:";
                text: spool-display.spool-record.note;
                text-wrap: mode == SpoolDisplayMode.ImportTagDefinition ? word-wrap : no-wrap;
            }

            LabeledInfo {
                vertical-stretch: 1;
                label: "In Slicer:";
                text: spool-display.slicer-filament-name;
            }

            HorizontalLayout {
                vertical-stretch: 1;
                alignment: space-between;
                LabeledInfo {
                    horizontal-stretch: 1;
                    label: "Color:";
                    text: "\{spool-display.spool-record.color-code}";
                }
            }

            if mode != SpoolDisplayMode.ImportTagDefinition: HorizontalLayout {
                vertical-stretch: 1;
                alignment: space-between;
                LabeledInfo {
                    horizontal-stretch: 1;
                    label: "PA(K):";
                    text: spool-display.pa-line1;
                }
                LabeledInfo {
                    label: "Temps: ";
                    label-width: 70px;
                    text: "\{spool-display.temp-min}°C - \{spool-display.temp-max}°C";
                }
            }

            if mode != SpoolDisplayMode.ImportTagDefinition: LabeledInfo {
                vertical-stretch: 1;
                label: "Location:";
                text: spool-display.assigned-location!="" ? spool-display.assigned-location + " (Assigned)" : "No Assigned Location";
            }

            HorizontalLayout {
                vertical-stretch: 1;
                VerticalLayout {
                    LabeledInfo {
                        width: 90px;
                        label: "Weights:";
                        text: "";
                    }
                }

                WeightsDisplay {
                    pure function calc-net(weight_new: int, weight_current: int, weight_core: int, weight_advertised: int, consumed_since_weight: float) -> int {
                        // code from inventory adjusted to here
                        return (weight_current != 0 && weight_core != 0 ? weight_current - weight_core : (weight_current != 0 && weight_advertised != 0 && weight_new != 0 ? weight_current - (weight_new - weight_advertised) : 0)) - Math.round(consumed_since_weight * 10) / 10;
                    }
                    property <string> core: spool-display.spool-record.weight-core > 0 ? "\{spool-display.spool-record.weight-core}g" : "-";
                    property <string> new: spool-display.spool-record.weight-new > 0 ? "\{spool-display.spool-record.weight-new}g" : "-";
                    property <string> advertised: spool-display.spool-record.weight-advertised <= 0 ? "-" : ((spool-display.spool-record.weight-advertised > 500) && (Math.mod(spool-display.spool-record.weight-advertised,500)) == 0) ? "\{spool-display.spool-record.weight-advertised / 1000}kg" : "\{spool-display.spool-record.weight-advertised}g";
                    property <string> gross: spool-display.spool-record.weight-current > 0 ? "\{spool-display.spool-record.weight-current}g" : "-";
                    property <int> net_value: calc-net(spool-display.spool-record.weight-new, spool-display.spool-record.weight-current, spool-display.spool-record.weight-core, spool-display.spool-record.weight-advertised, spool-display.spool-record.consumed-since-weight);
                    property <string> net: net_value != 0 ? "\{net_value}g" : "-";

                    weight-label: advertised;
                    weight-empty: core;
                    weight-full: new;
                    weight-net: net;
                    weight-gross: gross;
                }
            }
        }
    }
}
