import { MyText, MyButton } from "framework/widgets.slint";
import { AppState, AppConsts, AppBackend, SpoolStagingState, ControlState, SpoolScaleState, StagingOperationsPage } from "app.slint";
import { Utils } from "utils.slint"; 
import { FrameworkState } from "framework/framework.slint";

export component SpoolStaging inherits Rectangle {
    callback clicked-ota;

    main := VerticalLayout {
        spacing: AppConsts.trays-spacing;
        title := Rectangle {
            background: AppConsts.title-gradient;
            height: 30px;
            Text {
                color: white; // Utils.contrasting_color(parent.background); // entered manually white because this cause a panic in slint for some reason
                text: AppState.spool-staging-state == SpoolStagingState.Empty ? "Staging" : AppState.spool-staging-state == SpoolStagingState.Scanned ? "Scanned" : AppState.spool-staging-state == SpoolStagingState.Encoded ? "Encoded" : "Unloaded";
                font-size: 20px;
            }

            title-border := Rectangle {
                border-color: black;
                border-width: 1px;
            }
        }

        Rectangle {
            filament-box := Rectangle {
                background: (AppState.spool-staging-state != SpoolStagingState.Empty) ? AppState.spool-staging-info.color : AppConsts.no-color;

                if AppState.spool-staging-state != SpoolStagingState.Empty: 
                VerticalLayout {
                    property <bool> show-weight: AppState.spool-staging-info.spool-record.weight-core > 0;
                    alignment: space-around;
                    padding-top: 8px;
                    padding-bottom: 8px;

                  // inventory-id
                  if AppState.spool-staging-info.spool-record.id != "": inventory-id := Text {
                        horizontal-alignment: center;
                        font-size: 20px;
                        text: AppState.spool-staging-info.spool-record.id != "" ? "ID: \{AppState.spool-staging-info.spool-record.id}" : "";
                        color: Utils.contrasting_color(filament-box.background);
                    }

                    material := Text {
                        horizontal-alignment: center;
                        font-size: 20px;
                        text: AppState.spool-staging-info.spool-record.material-type;
                        color: Utils.contrasting_color(filament-box.background);
                    }

                    if AppState.spool-staging-info.weight-left != "": Text {
                        horizontal-alignment: center;
                        font-size: 20px;
                        text: AppState.spool-staging-info.weight-left;
                        color: Utils.contrasting_color(filament-box.background);
                    }

                  // K Value (show only if no ID, otherwiser no room)
                  if AppState.spool-staging-info.weight-left == "": k-value := Text {
                        horizontal-alignment: center;
                        font-size: 20px;
                        text: "K: " + (AppState.spool-staging-info.spool-record.ext-has-k ? "✔" : "-");
                        color: Utils.contrasting_color(filament-box.background);
                    }
                }
            }

            if (AppState.spool-staging-state == SpoolStagingState.Empty && (AppState.stable-firmware-updates-available() || AppState.unstable-firmware-updates-available())): 
            Rectangle {
                width: parent.width;
                height: parent.height;

                MyText {
                    color: lightgreen;
                    horizontal-alignment: center;
                    vertical-alignment: center;

                    text: AppState.stable-firmware-updates-available() ? "Updates\nAvailable" : "Beta\nUpdates\nAvailable";
                }
            }

            filament-box-border := Rectangle {
                width: parent.width;
                height: parent.height;
                border-color: black;
                border-width: 1px;
            }
        }
    }

    if (AppState.highlight-tray == 999 && AppState.highlight-tray-flash) || (AppState.highlight-staging): highlight-border := Rectangle {
        width: parent.width;
        height: parent.height;
        border-width: 4px;
        border-color: Utils.contrasting_color(filament-box.background);
    }

    area := TouchArea {
        width: parent.width;
        height: parent.height;
        clicked => {
            AppState.staging-selected();
            if AppState.spool-staging-state == SpoolStagingState.Empty {
                AppState.staging-operation-page = StagingOperationsPage.SelectSpoolToLoad;
            }
        }
    }
}
