import { MyText, MyButton, ButtonType, WizardButtons, Title } from "framework/widgets.slint";
import { AppBackend, AppState, ControlState, SpoolStagingState, SpoolScaleState, StagingOperationsPage, UiSpoolRecordDisplay } from "app.slint";
import { SpoolDisplay } from "spool-display.slint";
import { Utils } from "utils.slint";
import { ScaleWeightDisplay } from "app-widgets.slint";
import { UpdateWeightPage } from "common-operations.slint";
import { LocationDisplay } from "location-display.slint";
import { NumPad } from "numpad.slint";

component SpoolDisplayStep inherits Rectangle {
    callback more-clicked();
    in property <UiSpoolRecordDisplay> spool-display;
    VerticalLayout {

        SpoolDisplay {
            spool-display: root.spool-display;
        }

        HorizontalLayout {
            height: 56px;
            if AppState.spool-scale-state != SpoolScaleState.NotAvailable: MyButton {
                enabled: AppState.spool-staging-state != SpoolStagingState.Empty && AppState.is-scale-usable-now();
                text: "Quick Weight";
                clicked => {
                    AppBackend.set-spool-weight(spool-display.spool-record.id, AppState.spool-scale-weight, -1, false);
                }
            }

            if AppState.spool-scale-state == SpoolScaleState.NotAvailable: MyButton {
                text: "Configure Slot";
                clicked => {
                    AppState.control-state = ControlState.TraySelect;
                }
            }

            MyButton {
                text: "More...";
                clicked => {
                    AppState.staging-operation-page = StagingOperationsPage.OperationSelection;
                }
            }

            MyButton {
                text: "Close";
                clicked => {
                    AppState.prompt-select-tray();
                }
            }
        }
    }
}

component OperationSelectionStep inherits Rectangle {
    background: white;
    VerticalLayout {
        Title {
            text: "Please Select Staging Operation";
        }

        GridLayout {
            padding: 5px;
            spacing: 5px;
            Row {
                MyButton {
                    text: "Configure Slot Manually";
                    clicked => {
                        AppState.control-state = ControlState.TraySelect;
                    }
                }

                MyButton {
                    enabled: AppState.spool-staging-state != SpoolStagingState.Empty && AppState.is-scale-usable-now();
                    text: "Advanced Weight";
                    clicked => {
                        AppState.prev-staging-operation-page = AppState.staging-operation-page;
                        AppState.staging-operation-page = StagingOperationsPage.UpdateWeight;
                    }
                }

                MyButton {
                    text: "Clear Staging";
                    clicked => {
                        AppBackend.clear-staging();
                        AppState.control-state = ControlState.Ready;
                    }
                }
            }

            Row {
                MyButton {
                    text: "Encode Tag";
                    clicked => {
                        AppState.encode-start();
                    }
                }

                MyButton {
                    text: "Unlink Tag";
                    clicked => {
                        AppBackend.unlink-spool-from-tag(AppState.spool-staging-info.spool-record.id)
                    }
                }

                MyButton {
                    text: "Erase Tag";
                    clicked => {
                        AppState.erase-tag-by-spool-id-start(AppState.spool-staging-info.spool-record.id)
                    }
                }
            }

            Row {
                MyButton {
                    visible: true;
                    enabled: AppState.spool-staging-info.spool-record.actual-location != "" || AppState.spool-staging-info.spool-record.assigned-location != "";
                    text: AppState.spool-staging-info.spool-record.actual-location != "" ? "Picked from Storage" : "Place in Assigned Spot";
                    clicked => {
                        if (AppState.spool-staging-info.spool-record.actual-location != "") {
                            AppBackend.update-actual-location(AppState.spool-staging-info.spool-record.id, "", "Cleared Spool's Actual Location");
                        } else {
                            AppState.staging-operation-page = StagingOperationsPage.PlaceSpoolInAssignedLocation;
                        }
                    }
                }

                MyButton {
                    visible: false;
                    enabled: false;
                    text: "Mark as Dried";
                }

                MyButton {
                    // for used up spools it needs to show "mark refilled", and start process of weighting;
                    // used up should clear the weights/fill the used, and mark it as used etc.
                    visible: false;
                    enabled: false;
                    text: "Mark Used-Up";
                }
            }
        }

        HorizontalLayout {
            MyButton {
                height: 56px;
                text: "Close";
                clicked => {
                    AppState.control-state = ControlState.Ready;
                }
            }
        }
    }
}

component PlaceSpoolInAssignedLocationStep inherits Rectangle {
    width: 480px;
    height: 320px;
    background: white;
    in property <UiSpoolRecordDisplay> spool-display;

    property <string> brand: spool-display.spool-record.brand == "" ? "" : "\{spool-display.spool-record.brand} ";
    property <string> material-subtype: spool-display.spool-record.material-subtype == "" ? "" : " \{spool-display.spool-record.material_subtype}";
    property <string> color-name: spool-display.spool-record.color-name == "" ? "" : " \{spool-display.spool-record.color-name}";
    VerticalLayout {
        alignment: space-between;

        VerticalLayout {
            spacing: 10px;
            Title {
                text: "Place Spool \{spool-display.spool-record.id} in Assigned Location";
            }

            VerticalLayout {
                padding-left: 10px;
                padding-right: 10px;
                spacing: 10px;
                MyText {
                    vertical-stretch: 1;
                    horizontal-alignment: center;
                    text: "\{brand}\{spool-display.spool-record.material-type}\{material-subtype}\{color-name}";
                }

                MyText {
                    text: "Spool's assigned location";
                }

                LocationDisplay {
                    location: AppBackend.location-str-to-location(spool-display.spool-record.assigned-location);
                }
            }
        }

        WizardButtons {
            next-text: "Placed Spool";
            next-enabled: true;
            back-enabled: true;
            next-clicked => {
                AppBackend.update-actual-location(AppState.spool-staging-info.spool-record.id, AppState.spool-staging-info.spool-record.assigned-location, "Updated Spool's Actual Location\nto its Assigned Location");
                AppState.control-state = ControlState.Ready;
            }
            back-clicked => {
                AppState.staging-operation-page = StagingOperationsPage.OperationSelection;
            }
            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
        }
    }
}

component SelectSpoolToLoadStep inherits Rectangle {
    width: 480px;
    height: 320px;
    background: white;
    VerticalLayout {
        Title {
            text: "Enter Spool ID to Load to Staging";
        }

        Rectangle {
            num-pad := NumPad {
                number: AppState.new-tag-scan-spool-id-int;
                ok-visible: false;
                display-postfix: "";
            }
        }

        WizardButtons {
            next-text: "Load Spool";
            next-enabled: true;
            back-enabled: false;
            next-clicked => {
                num-pad.display-error = AppBackend.load-staging(num-pad.number);
                if num-pad.display-error == "" {
                    AppState.control-state = ControlState.Ready;
                }
            }
            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
        }
    }
}

export component StagingOperations {
    property <UiSpoolRecordDisplay> spool-display: AppBackend.get-spool-record-display(AppState.spool-staging-info.spool-record.id);
    if AppState.staging-operation-page == StagingOperationsPage.SpoolDisplay: SpoolDisplayStep {
        spool-display: spool-display;
    }
    if AppState.staging-operation-page == StagingOperationsPage.OperationSelection: OperationSelectionStep { }
    if AppState.staging-operation-page == StagingOperationsPage.UpdateWeight: UpdateWeightPage {
        title: "Update Spool \{spool-display.spool-record.id} Weight";
        user-prompt: "Please place the spool on the scale:";
        weight-current: spool-display.spool-record.weight-current;
        weight-new: spool-display.spool-record.weight-new;
        spool-id: spool-display.spool-record.id;
        cancel-clicked => {
            AppState.control-state = ControlState.Ready;
        }
        back-clicked => {
            AppState.staging-operation-page = AppState.prev-staging-operation-page;
        }
    }
    if AppState.staging-operation-page == StagingOperationsPage.PlaceSpoolInAssignedLocation: PlaceSpoolInAssignedLocationStep {
        spool-display: spool-display;
    }
    if AppState.staging-operation-page == StagingOperationsPage.SelectSpoolToLoad: SelectSpoolToLoadStep { }
}
