import { MyText, MyButton, ButtonType, WizardButtons, Title } from "framework/widgets.slint";
import { AppBackend, AppState, ControlState, SpoolStagingState, SpoolScaleState, UiFilamentState, UiSpoolRecordDisplay, UiTray } from "app.slint";
import { SpoolDisplay, MultiColorTitle } from "spool-display.slint";
import { SlotDisplay } from "slot-display.slint";
import { Utils } from "utils.slint";


enum TrayDisplayTab {
    Slot,
    Spool
}

component TrayDisplayStep inherits Rectangle {
    callback more-clicked();
    property <TrayDisplayTab> tab: spool-id != "" ? TrayDisplayTab.Spool : TrayDisplayTab.Slot;
    in property <string> spool-id: "1";
    in property <int> tray-index;
    property <UiSpoolRecordDisplay> spool-display: AppBackend.get-spool-record-display(spool-id);
    VerticalLayout {
        HorizontalLayout {
            vertical-stretch: 0;
            height: 40px;
            MultiColorTitle {
                width: spool-id != "" ? 240px : 480px; // must force width with MultiColorTitle
                push-button: true;
                text: "Slot \{AppState.trays-state[tray-index].name} Information";
                colors: AppState.trays-state[tray-index].filament.colors;
                pushed: root.tab == TrayDisplayTab.Slot;
                pressed => {
                    root.tab = TrayDisplayTab.Slot
                }
            }

            if spool-id != "": MultiColorTitle {
                width:240px; // must force width with MultiColorTitle
                push-button: true; 
                text: "Spool \{spool-id} Information";
                pushed: tab == TrayDisplayTab.Spool;
                colors: root.spool-display.colors;
                pressed => {
                    root.tab = TrayDisplayTab.Spool
                }
            }
        }

        if root.tab == TrayDisplayTab.Spool: SpoolDisplay {
            vertical-stretch: 1;
            show-title: false;
            spool-display: root.spool-display;
        }
        if root.tab == TrayDisplayTab.Slot: SlotDisplay {
            vertical-stretch: 1;
            slot-index: root.tray-index;
        }

        HorizontalLayout {
            vertical-stretch: 0;
            height: 56px;
            MyButton {
                visible: false;
                text: "Unload";
            }

            MyButton {
                text: "More...";
                clicked => {
                    more-clicked();
                }
            }

            MyButton {
                text: "Close";
                clicked => {
                    AppState.control-state = ControlState.Ready;
                }
            }
        }
    }
}

component OperationSelectionStep inherits Rectangle {
    background: white;
    in property <int> tray-index;

    VerticalLayout {
        Title {
            text: "Please Select Slot Operation";
        }

        GridLayout {
            padding: 5px;
            spacing: 5px;
            Row {
                MyButton {
                    enabled: AppState.trays-state[tray-index].spool_rec_id != "";
                    text: "Untag Slot";
                    clicked => {
                        AppBackend.untag-slot(AppState.trays-state[tray-index].id);
                        AppState.control-state = ControlState.Ready;
                    }
                }

                MyButton {
                    enabled: AppState.spool-staging-state != SpoolStagingState.Empty;
                    text: "Configure from Staging";
                    clicked => {
                        AppBackend.set-staging-to-tray(AppState.trays-state[tray-index].id);
                        AppState.control-state = ControlState.Ready;
                    }
                }

                MyButton {
                    text: "Reset Slot";
                    clicked => {
                        AppBackend.untag-slot(AppState.trays-state[tray-index].id);
                        AppBackend.reset-slot(AppState.trays-state[tray-index].id);
                        AppState.control-state = ControlState.Ready;
                    }
                }
            }

            Row {
                MyButton {
                    enabled: AppState.trays-state[tray-index].spool_rec_id != "";
                    text: "Reapply Tag";
                    clicked => {
                        AppBackend.configure-slot-with-spool-id(AppState.trays-state[tray-index].id,  AppState.trays-state[tray-index].spool_rec_id);
                        AppState.control-state = ControlState.Ready;
                    }
                }
                MyButton {
                    visible: false;
                    text: "Unload Filament";
                    clicked => {
                    }
                }
                MyButton { // just to have a second row
                  visible: false;
                }
            }
        }

        HorizontalLayout {
            MyButton {
                height: 56px;
                text: "Cancel";
                clicked => {
                    AppState.control-state = ControlState.Ready;
                }
            }
        }
    }
}

enum TrayOperationsPage {
  SpoolDisplay,
  OperationSelection,
}


export component TrayOperations inherits Rectangle {
    background: white;
    property <UiTray> ui-tray: AppState.trays-state[AppState.tray-selected-tray-index];
    property <TrayOperationsPage> page: ui-tray.filament.state == UiFilamentState.Known || ui-tray.spool-rec-id != "" ? TrayOperationsPage.SpoolDisplay : TrayOperationsPage.OperationSelection;
    if page == TrayOperationsPage.SpoolDisplay: TrayDisplayStep {
        spool-id: AppState.trays-state[AppState.tray-selected-tray-index].spool_rec_id;
        tray-index: AppState.tray-selected-tray-index;
        more-clicked => {
            page = TrayOperationsPage.OperationSelection;
        }
    }
    if page == TrayOperationsPage.OperationSelection: OperationSelectionStep {
        tray-index: AppState.tray-selected-tray-index;
    }
}
