import { FrameworkState } from "framework/framework.slint";
import { MyButton, Title } from "framework/widgets.slint";
import { AppBackend, AppState, ControlState, SpoolStagingState, UiFilamentState, UiSlot, UiSpoolRecordDisplay } from "app.slint";
import { SpoolDisplay, MultiColorTitle } from "spool-display.slint";
import { SlotDisplay } from "slot-display.slint";

enum SlotDisplayTab {
    Slot,
    Spool
}

component SlotDisplayStep inherits Rectangle {
    callback more-clicked();
    in property <UiSlot> slot;
    property <string> spool-id: slot.spool-id;
    property <SlotDisplayTab> tab: spool-id != "" ? SlotDisplayTab.Spool : SlotDisplayTab.Slot;
    property <UiSpoolRecordDisplay> spool-display: AppBackend.get-spool-record-display(spool-id);

    VerticalLayout {
        HorizontalLayout {
            vertical-stretch: 0;
            height: 40px;
            MultiColorTitle {
                width: spool-id != "" ? FrameworkState.display-width / 2 : FrameworkState.display-width;
                push-button: true;
                text: "Slot \{slot.name} Information";
                colors: slot.filament.colors;
                pushed: root.tab == SlotDisplayTab.Slot;
                pressed => {
                    root.tab = SlotDisplayTab.Slot;
                }
            }

            if spool-id != "": MultiColorTitle {
                width: FrameworkState.display-width / 2;
                push-button: true;
                text: "Spool \{spool-id} Information";
                pushed: tab == SlotDisplayTab.Spool;
                colors: root.spool-display.colors;
                pressed => {
                    root.tab = SlotDisplayTab.Spool;
                }
            }
        }

        if root.tab == SlotDisplayTab.Spool: SpoolDisplay {
            vertical-stretch: 1;
            show-title: false;
            spool-display: root.spool-display;
        }

        if root.tab == SlotDisplayTab.Slot: SlotDisplay {
            vertical-stretch: 1;
            slot: root.slot;
        }

        HorizontalLayout {
            vertical-stretch: 0;
            height: 56px;
            MyButton {
                visible: false;
                text: "Unload";
            }

            MyButton {
                text: "More...";
                clicked => {
                    more-clicked();
                }
            }

            MyButton {
                text: "Close";
                clicked => {
                    AppState.control-state = ControlState.Ready;
                }
            }
        }
    }
}

component OperationSelectionStep inherits Rectangle {
    background: white;
    in property <UiSlot> slot;

    VerticalLayout {
        Title {
            text: "Please Select Slot Operation";
        }

        GridLayout {
            padding: 5px;
            spacing: 5px;
            Row {
                MyButton {
                    enabled: slot.spool-id != "" && AppState.curr-printer-can-unassign-slot();
                    text: "Untag Slot";
                    clicked => {
                        AppBackend.unassign-slot(slot.id);
                        AppState.control-state = ControlState.Ready;
                    }
                }

                MyButton {
                    enabled: AppState.spool-staging-state != SpoolStagingState.Empty && AppState.curr-printer-can-configure-slot();
                    text: "Configure from Staging";
                    clicked => {
                        AppBackend.set-staging-to-slot(slot.id);
                        AppState.control-state = ControlState.Ready;
                    }
                }

                MyButton {
                    enabled: AppState.curr-printer-can-clear-slot();
                    text: "Reset Slot";
                    clicked => {
                        AppBackend.unassign-slot(slot.id);
                        AppBackend.reset-slot(slot.id);
                        AppState.control-state = ControlState.Ready;
                    }
                }
            }

            Row {
                MyButton {
                    enabled: slot.spool-id != "" && AppState.curr-printer-can-configure-slot();
                    text: "Reapply Tag";
                    clicked => {
                        AppBackend.configure-slot-with-spool-id(slot.id, slot.spool-id);
                        AppState.control-state = ControlState.Ready;
                    }
                }
                MyButton {
                    visible: false;
                    text: "Unload Filament";
                }
                MyButton {
                    visible: false;
                }
            }
        }

        HorizontalLayout {
            MyButton {
                height: 56px;
                text: "Cancel";
                clicked => {
                    AppState.control-state = ControlState.Ready;
                }
            }
        }
    }
}

enum SlotOperationsPage {
  SpoolDisplay,
  OperationSelection,
}

export component TrayOperations inherits Rectangle {
    background: white;
    property <UiSlot> slot: AppState.selected-slot;
    property <SlotOperationsPage> page: slot.filament.state == UiFilamentState.Known || slot.spool-id != "" ? SlotOperationsPage.SpoolDisplay : SlotOperationsPage.OperationSelection;

    if page == SlotOperationsPage.SpoolDisplay: SlotDisplayStep {
        slot: root.slot;
        more-clicked => {
            page = SlotOperationsPage.OperationSelection;
        }
    }

    if page == SlotOperationsPage.OperationSelection: OperationSelectionStep {
        slot: root.slot;
    }
}
