name: Desktop 

on:
  push:
    branches: [ "main" ]
    paths:
      - 'desktop/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'desktop/**'
  workflow_dispatch:  # Allows manual trigger
  workflow_call:
    outputs:
      artifact_Mac1:
        description: "MacOS DMG"
        value: SpoolEaseDesktop-MacOS-Dmg
      artifact_Mac2:
        description: "MacOS App Folder"
        value: SpoolEaseDesktop-MacOS-App-Folder
      artifact_Win1:
        description: "Windows Msi"
        value: SpoolEaseDesktop-Windows-Msi
      artifact_Win2:
        description: "Windows Nsis Setup"
        value: SpoolEaseDesktop-Windows-Nsis-Setup

env:
  CARGO_TERM_COLOR: always

jobs:
  buildMac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update Rust
      run: rustup update
    - uses: cargo-bins/cargo-binstall@main
    - name: Get dioxus
      run: cargo binstall -y dioxus-cli
    - name: Environment details
      run: |
        rustup toolchain list
        dx --version
    - name: Build
      run: |
        cd desktop
        dx bundle --out-dir ./bundle
    - name: Upload macOS DMG
      uses: actions/upload-artifact@v4
      with:
        name: SpoolEaseDesktop-MacOS-Dmg
        path: /Users/runner/work/SpoolEase/SpoolEase/desktop/bundle/*.dmg
    - name: Upload macOS Bundle Folder
      uses: actions/upload-artifact@v4
      with:
        name: SpoolEaseDesktop-MacOS-App-Folder
        path: /Users/runner/work/SpoolEase/SpoolEase/desktop/bundle/SpoolEaseDesktop.app

  buildWindows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update Rust
      run: rustup update
    - uses: cargo-bins/cargo-binstall@main
    - name: Get dioxus
      run: cargo binstall -y dioxus-cli
    - name: Environment details
      run: |
        rustup toolchain list
        dx --version
    - name: list files
      run: tree /F
    - name: Build
      run: |
        cd desktop
        dx bundle
    - name: Upload Windows Msi
      uses: actions/upload-artifact@v4
      with:
        name: SpoolEaseDesktop-Windows-Msi
        path: D:\a\SpoolEase\SpoolEase\target\dx\SpoolEaseDesktop\bundle\windows\bundle\msi\*.msi
    - name: Upload Windows Nsis Setup
      uses: actions/upload-artifact@v4
      with:
        name: SpoolEaseDesktop-Windows-Nsis-Setup
        path: D:\a\SpoolEase\SpoolEase\target\dx\SpoolEaseDesktop\bundle\windows\bundle/nsis/*.exe
